import type{LearningEvidence,PerformancePattern,PerformancePatternDimension}from"@kairo/domain/learning";

export interface PublishedCreativeObservation{publishedPostId:string;metricObservationIds:string[];score:number;topic?:string;hook?:string;structure?:string;template?:string;format?:string;publishedAt?:string}

export function identifyPerformancePatterns(input:PublishedCreativeObservation[]):PerformancePattern[]{const rows=input.filter(validObservation),patterns:PerformancePattern[]=[];for(const dimension of["topic","hook","structure","template","format"]as const){const groups=group(rows,dimension);const winner=winnerGroup(groups);if(winner)patterns.push(pattern(dimension,winner.value,winner.rows,`Highest average observed score (${round(average(winner.rows))}) among ${groups.size} compared ${dimension} values. This is a correlation in the available sample, not proof of causation.`))}const timingRows=rows.filter(row=>row.publishedAt&&Number.isFinite(Date.parse(row.publishedAt)));const timingGroups=new Map<string,PublishedCreativeObservation[]>();for(const row of timingRows){const date=new Date(row.publishedAt!),value=`${new Intl.DateTimeFormat("en",{weekday:"long",timeZone:"UTC"}).format(date)} ${String(date.getUTCHours()).padStart(2,"0")}:00 UTC`;timingGroups.set(value,[...(timingGroups.get(value)??[]),row])}const timing=winnerGroup(timingGroups);if(timing)patterns.push(pattern("timing",timing.value,timing.rows,`Highest average observed score (${round(average(timing.rows))}) among ${timingGroups.size} compared UTC time buckets. Test again before treating this as a preferred posting time.`));return patterns}
function validObservation(row:PublishedCreativeObservation){return Boolean(row&&row.publishedPostId&&Array.isArray(row.metricObservationIds)&&row.metricObservationIds.length&&Number.isFinite(row.score)&&row.score>=0)}
function group(rows:PublishedCreativeObservation[],dimension:Exclude<PerformancePatternDimension,"timing">){const groups=new Map<string,PublishedCreativeObservation[]>();for(const row of rows){const value=row[dimension]?.trim();if(value)groups.set(value,[...(groups.get(value)??[]),row])}return groups}
function winnerGroup(groups:Map<string,PublishedCreativeObservation[]>){if(groups.size<2)return undefined;const eligible=[...groups.entries()].filter(([,rows])=>rows.length>=2).map(([value,rows])=>({value,rows}));return eligible.sort((a,b)=>average(b.rows)-average(a.rows)||b.rows.length-a.rows.length||a.value.localeCompare(b.value))[0]}
function average(rows:PublishedCreativeObservation[]){return rows.reduce((sum,row)=>sum+row.score,0)/rows.length}
function round(value:number){return Number(value.toFixed(4))}
function pattern(dimension:PerformancePatternDimension,value:string,rows:PublishedCreativeObservation[],observation:string):PerformancePattern{return{dimension,value,observation,evidence:evidence(rows)}}
function evidence(rows:PublishedCreativeObservation[]):LearningEvidence[]{const grouped=new Map<string,string[]>();for(const row of rows)grouped.set(row.publishedPostId,[...new Set([...(grouped.get(row.publishedPostId)??[]),...row.metricObservationIds])]);return[...grouped.entries()].map(([publishedPostId,metricObservationIds])=>({publishedPostId,metricObservationIds}))}
