import { describe,expect,it,vi } from "vitest";
import { applyPublishAttempt,beginPublishAttempt,connectChannelAccount,createPublishCommand } from "@kairo/domain/publishing";
import type { ContentApproval } from "@kairo/domain/review";
import { BoundedPublishVerifier } from "./publish-verification";

const approval:ContentApproval={id:"approval-1",reviewId:"review-1",approverAccountId:"human",workspaceId:"ws",brandId:"brand",campaignId:"campaign",assetId:"asset",versionId:"content-v2",version:2,destination:{channel:"instagram",accountRef:"123"},approvedAt:"2026-08-15T10:00:00Z"};
function publishing(){const account=connectChannelAccount({id:"channel",workspaceId:"ws",brandId:"brand",channel:"instagram",accountRef:"123",displayName:"IG",credentialRef:"vault://ig",authMethod:"facebook-login",capabilities:["publish-image"],connectedAt:"2026-08-15T10:00:00Z"}),command=createPublishCommand({id:"command",approval,currentVersionId:"content-v2",channelAccount:account,contentType:"image",mediaItems:[{kind:"image",url:"https://media.example.test/approved.png"}],scheduledFor:"2026-08-15T10:01:00Z",createdAt:"2026-08-15T10:00:00Z"});return applyPublishAttempt(command,beginPublishAttempt({id:"attempt",command,startedAt:"2026-08-15T10:01:00Z"}))}
describe("BoundedPublishVerifier",()=>{
  it("moves Approved through Publishing and Processing to Published",async()=>{const command=publishing(),sleep=vi.fn(),statuses=vi.fn().mockResolvedValueOnce({status:"processing"}).mockResolvedValueOnce({status:"published",publishId:"media-1",publishedUrl:"https://www.instagram.com/p/media-1/"}),result=await new BoundedPublishVerifier({getStatus:statuses},{maxChecks:3,intervalMs:1,sleep},()=>new Date("2026-08-15T10:02:00Z")).verify(command,"container-1");expect(command.lifecycleStatus).toBe("publishing");expect(result).toMatchObject({lifecycleStatus:"published",metaContainerId:"container-1",providerPublishId:"media-1"});expect(sleep).toHaveBeenCalledOnce()});
  it("moves Processing to Failed with a bounded provider reason",async()=>{const result=await new BoundedPublishVerifier({getStatus:async()=>({status:"failed",failureReason:"provider-media-processing-error"})},{maxChecks:2,intervalMs:0,sleep:async()=>undefined},()=>new Date("2026-08-15T10:02:00Z")).verify(publishing(),"container-2");expect(result).toMatchObject({lifecycleStatus:"failed",failureReason:"provider-media-processing-error"})});
  it("fails closed after the bounded Processing poll window",async()=>{const status=vi.fn(async()=>({status:"processing" as const})),result=await new BoundedPublishVerifier({getStatus:status},{maxChecks:2,intervalMs:0,sleep:async()=>undefined},()=>new Date("2026-08-15T10:02:00Z")).verify(publishing(),"container-3");expect(result).toMatchObject({lifecycleStatus:"failed",failureReason:"provider-processing-timeout"});expect(status).toHaveBeenCalledTimes(2)});
});
