import type{ChannelAuthMethod,PublishChannel,PublishContentType,PublishMediaItem,PublishOptions}from"@kairo/domain/publishing";
export interface PublishingJob{commandId:string;versionId:string;approvedAssetVersionId?:string;approvedMediaFingerprint?:string;attemptId:string;attemptNumber:number;leaseOwner:string;idempotencyKey:string;channel:PublishChannel;accountRef:string;credentialRef:string;authMethod?:ChannelAuthMethod;contentType:PublishContentType;content:string;mediaUrls:string[];mediaItems?:PublishMediaItem[];options?:PublishOptions}
export type ProviderPublishResult={status:"published";externalPostId:string;providerCorrelationId?:string;publishedUrl?:string}|{status:"failed";failureCode:string;retryable:boolean;retryAfterSeconds?:number;providerCorrelationId?:string}|{status:"unknown";providerCorrelationId?:string}|{status:"manual-required";reason:string};
export interface PublishingAdapter{readonly channel:Exclude<PublishChannel,"manual">;supports(job:PublishingJob):boolean;publish(job:PublishingJob):Promise<ProviderPublishResult>}
export interface PublishingExecutor{execute(job:PublishingJob):Promise<ProviderPublishResult>}
export class DeterministicPublishingWorker{constructor(private adapters:PublishingAdapter[]){}async execute(job:PublishingJob):Promise<ProviderPublishResult>{if(job.channel==="manual")return{status:"manual-required",reason:"Manual destination selected"};const adapter=this.adapters.find(x=>x.channel===job.channel&&x.supports(job));if(!adapter)return{status:"manual-required",reason:`${job.channel} ${job.contentType} publishing is unavailable`};return adapter.publish(job)}}
export interface ApprovedMediaDeliveryPort{deliver(input:{commandId:string;approvedAssetVersionId:string;approvedMediaFingerprint:string}):Promise<{approvedAssetVersionId:string;approvedMediaFingerprint:string;mediaItems:PublishMediaItem[];expiresAt:string}>}
export class ApprovedMediaPublishingWorker{constructor(private publishing:DeterministicPublishingWorker,private delivery?:ApprovedMediaDeliveryPort,private now:()=>Date=()=>new Date()){}async execute(job:PublishingJob):Promise<ProviderPublishResult>{if(job.contentType!=="carousel")return this.publishing.execute(job);if(!this.delivery)return{status:"failed",failureCode:"approved-media-delivery-unavailable",retryable:false};required(job.versionId,"versionId");const version=required(job.approvedAssetVersionId,"approvedAssetVersionId"),fingerprint=required(job.approvedMediaFingerprint,"approvedMediaFingerprint");const delivered=await this.delivery.deliver({commandId:job.commandId,approvedAssetVersionId:version,approvedMediaFingerprint:fingerprint});if(delivered.approvedAssetVersionId!==version||delivered.approvedMediaFingerprint!==fingerprint)return{status:"failed",failureCode:"approved-media-mismatch",retryable:false};const expires=Date.parse(delivered.expiresAt);if(!Number.isFinite(expires)||expires<=this.now().getTime())return{status:"failed",failureCode:"publishing-url-expired",retryable:true};if(!Array.isArray(delivered.mediaItems)||!delivered.mediaItems.length)return{status:"failed",failureCode:"approved-media-unavailable",retryable:false};return this.publishing.execute({...job,mediaItems:delivered.mediaItems,mediaUrls:delivered.mediaItems.map(item=>item.url)})}}
export interface PublishingExecutionStore{claimNext(now:string,leaseOwner:string,leaseSeconds:number):Promise<PublishingJob|null>;settle(job:PublishingJob,result:ProviderPublishResult,at:string):Promise<void>}
export class PublishingJobRunner{constructor(private store:PublishingExecutionStore,private worker:PublishingExecutor,private leaseOwner:string,private leaseSeconds=60,private now:()=>Date=()=>new Date()){}async runOnce(){const job=await this.store.claimNext(this.now().toISOString(),this.leaseOwner,this.leaseSeconds);if(!job)return false;const result=await this.worker.execute(job);await this.store.settle(job,result,this.now().toISOString());return true}}
function required(value:unknown,field:string){if(typeof value!=="string"||!value.trim())throw new Error(`${field} is required`);return value.trim()}
