import{ConcurrencyConflictError,DomainValidationError}from"./index";
export interface LearningEvidence{publishedPostId:string;metricObservationIds:string[]}
export interface Contradiction extends LearningEvidence{note:string}
export const PERFORMANCE_PATTERN_DIMENSIONS=["topic","hook","structure","template","format","timing"]as const;
export type PerformancePatternDimension=typeof PERFORMANCE_PATTERN_DIMENSIONS[number];
export interface PerformancePattern{dimension:PerformancePatternDimension;value:string;observation:string;evidence:LearningEvidence[]}
export interface CandidateLearning{id:string;workspaceId:string;brandId:string;statement:string;interpretation:string;confidence:number;period:{from:string;to:string};applicability:{channel?:string;audience?:string;format?:string};patterns:PerformancePattern[];evidence:LearningEvidence[];contradictions:Contradiction[];status:"candidate"|"accepted"|"rejected"|"superseded";version:number;createdAt:string;decidedBy?:string;decidedAt?:string;rejectionReason?:string;supersededById?:string}
export interface Experiment{id:string;workspaceId:string;brandId:string;hypothesis:string;variants:Array<{id:string;description:string}>;primaryMetric:string;status:"draft"|"completed";createdAt:string;winnerVariantId?:string;resultSummary?:string;evidenceObservationIds?:string[];completedAt?:string}
export function createCandidateLearning(input:Omit<CandidateLearning,"status"|"version"|"contradictions"|"patterns">&{patterns?:PerformancePattern[]}):CandidateLearning{const evidence=evidenceList(input.evidence),patterns=patternList(input.patterns??[],evidence);causal(input.interpretation);const from=time(input.period.from,"period.from"),to=time(input.period.to,"period.to");if(Date.parse(from)>Date.parse(to))throw new DomainValidationError("Learning period is invalid");const applicability={...(input.applicability.channel?{channel:text(input.applicability.channel,"applicability.channel")} :{}),...(input.applicability.audience?{audience:text(input.applicability.audience,"applicability.audience")} :{}),...(input.applicability.format?{format:text(input.applicability.format,"applicability.format")} :{})};return{...input,id:text(input.id,"id"),workspaceId:text(input.workspaceId,"workspaceId"),brandId:text(input.brandId,"brandId"),statement:text(input.statement,"statement"),interpretation:text(input.interpretation,"interpretation"),confidence:confidence(input.confidence),period:{from,to},applicability,patterns,evidence,contradictions:[],status:"candidate",version:1,createdAt:time(input.createdAt,"createdAt")}}
export function acceptLearning(x:CandidateLearning,a:{actorType:"human"|"agent";actorId:string;at:string;expectedVersion:number}){human(a.actorType);current(x,a.expectedVersion);if(x.status!=="candidate")throw new DomainValidationError("Only Candidate Learnings can be accepted");return{...x,status:"accepted"as const,version:x.version+1,decidedBy:text(a.actorId,"actorId"),decidedAt:time(a.at,"at")}}
export function rejectLearning(x:CandidateLearning,a:{actorType:"human"|"agent";actorId:string;reason:string;at:string;expectedVersion:number}){human(a.actorType);current(x,a.expectedVersion);if(x.status!=="candidate")throw new DomainValidationError("Only Candidate Learnings can be rejected");return{...x,status:"rejected"as const,version:x.version+1,decidedBy:text(a.actorId,"actorId"),decidedAt:time(a.at,"at"),rejectionReason:text(a.reason,"reason")}}
export function correctLearning(x:CandidateLearning,a:{actorType:"human"|"agent";actorId:string;statement:string;interpretation:string;at:string;expectedVersion:number}){human(a.actorType);current(x,a.expectedVersion);if(x.status!=="candidate")throw new DomainValidationError("Only Candidate Learnings can be corrected");causal(a.interpretation);return{...x,statement:text(a.statement,"statement"),interpretation:text(a.interpretation,"interpretation"),version:x.version+1,decidedBy:text(a.actorId,"actorId"),decidedAt:time(a.at,"at")}}
export function addContradiction(x:CandidateLearning,c:Contradiction,nextConfidence:number,at:string){if(x.status!=="accepted")throw new DomainValidationError("Only accepted Learnings can receive contradictions");const item={...evidence(c),note:text(c.note,"note")};return{...x,confidence:confidence(nextConfidence),contradictions:[...x.contradictions,item],version:x.version+1,decidedAt:time(at,"at")}}
export function supersedeLearning(x:CandidateLearning,id:string,at:string){if(x.status!=="accepted")throw new DomainValidationError("Only accepted Learnings can be superseded");return{...x,status:"superseded"as const,supersededById:text(id,"supersededById"),decidedAt:time(at,"at"),version:x.version+1}}
export function createExperiment(input:Omit<Experiment,"status">):Experiment{if(input.variants.length<2)throw new DomainValidationError("Experiment requires at least two variants");const ids=input.variants.map(x=>text(x.id,"variant.id"));if(new Set(ids).size!==ids.length)throw new DomainValidationError("Experiment variant IDs must be unique");return{...input,id:text(input.id,"id"),workspaceId:text(input.workspaceId,"workspaceId"),brandId:text(input.brandId,"brandId"),hypothesis:text(input.hypothesis,"hypothesis"),variants:input.variants.map(x=>({id:text(x.id,"variant.id"),description:text(x.description,"variant.description")})),primaryMetric:text(input.primaryMetric,"primaryMetric"),createdAt:time(input.createdAt,"createdAt"),status:"draft"}}
export function completeExperiment(x:Experiment,r:{winnerVariantId:string;resultSummary:string;evidenceObservationIds:string[];completedAt:string}){if(x.status!=="draft")throw new DomainValidationError("Experiment is already complete");if(!x.variants.some(v=>v.id===r.winnerVariantId))throw new DomainValidationError("Winner must be an Experiment variant");if(!r.evidenceObservationIds.length)throw new DomainValidationError("Experiment result requires evidence");causal(r.resultSummary);return{...x,status:"completed"as const,winnerVariantId:r.winnerVariantId,resultSummary:text(r.resultSummary,"resultSummary"),evidenceObservationIds:unique(r.evidenceObservationIds,"evidenceObservationIds"),completedAt:time(r.completedAt,"completedAt")}}
function evidenceList(v:LearningEvidence[]){if(!v.length)throw new DomainValidationError("Learning requires supporting evidence");return v.map(evidence)}function evidence(v:LearningEvidence){return{publishedPostId:text(v.publishedPostId,"publishedPostId"),metricObservationIds:unique(v.metricObservationIds,"metricObservationIds")}}function unique(v:string[],f:string){if(!v.length)throw new DomainValidationError(`${f} is required`);const a=v.map(x=>text(x,f));if(new Set(a).size!==a.length)throw new DomainValidationError(`${f} must be unique`);return a}function causal(v:string){const n=text(v,"interpretation").toLowerCase();if(/\b(caused|guarantees?|proves?|definitely led)\b/.test(n)&&!/(not proof|not proven|does not prove|cannot prove)/.test(n))throw new DomainValidationError("Learning interpretation overstates causation")}function human(v:string){if(v!=="human")throw new DomainValidationError("Human authority is required")}function current(x:CandidateLearning,v:number){if(x.version!==v)throw new ConcurrencyConflictError("Learning changed")}function confidence(v:number){if(!Number.isFinite(v)||v<0||v>1)throw new DomainValidationError("confidence must be between 0 and 1");return v}function text(v:unknown,f:string){if(typeof v!=="string"||!v.trim())throw new DomainValidationError(`${f} is required`);if(v.trim().length>1000)throw new DomainValidationError(`${f} is too long`);return v.trim()}function time(v:unknown,f:string){const n=text(v,f);if(Number.isNaN(Date.parse(n)))throw new DomainValidationError(`${f} must be a valid timestamp`);return n}
function patternList(values:PerformancePattern[],allowedEvidence:LearningEvidence[]):PerformancePattern[]{if(!Array.isArray(values)||values.length>12)throw new DomainValidationError("Learning patterns are invalid");const allowed=new Set(allowedEvidence.flatMap(item=>item.metricObservationIds.map(id=>`${item.publishedPostId}\0${id}`)));return values.map((value,index)=>{if(!value||!PERFORMANCE_PATTERN_DIMENSIONS.includes(value.dimension))throw new DomainValidationError(`patterns[${index}].dimension is invalid`);const patternEvidence=evidenceList(value.evidence);if(patternEvidence.some(item=>item.metricObservationIds.some(id=>!allowed.has(`${item.publishedPostId}\0${id}`))))throw new DomainValidationError("Learning pattern evidence is outside the Learning evidence");return{dimension:value.dimension,value:text(value.value,`patterns[${index}].value`),observation:text(value.observation,`patterns[${index}].observation`),evidence:patternEvidence}})}
