import{ConcurrencyConflictError,DomainValidationError}from"./index";
export type WorkflowStage="brand-setup"|"hunter"|"research"|"generation"|"critic"|"publishing"|"metrics";
export type RetryDisposition="safe"|"manual-review"|"blocked";
export type CostKind="model"|"search"|"tool"|"social";
export type InterventionAction="retry-requested"|"automation-disabled"|"content-withdrawn"|"configuration-corrected"|"safety-reviewed";
export interface OperationalFailure{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly workflowId:string;readonly stage:WorkflowStage;readonly diagnosticCode:string;readonly summary:string;readonly retryDisposition:RetryDisposition;readonly attempt:number;readonly maxAttempts:number;readonly state:"failed";readonly occurredAt:string;readonly traceId?:string}
export interface RetryRequest{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly workflowId:string;readonly failureId:string;readonly attempt:number;readonly idempotencyKey:string;readonly requestedBy:string;readonly requestedAt:string}
export interface AutomationControl{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly automationKey:string;readonly stage:WorkflowStage;readonly status:"enabled"|"disabled";readonly version:number;readonly createdAt:string;readonly disabledAt?:string;readonly disabledBy?:string;readonly disabledReason?:string}
export interface CostEvent{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly workflowId:string;readonly kind:CostKind;readonly provider:string;readonly currency:string;readonly costMicros:number;readonly occurredAt:string}
export interface WorkflowBudget{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly workflowId:string;readonly currency:string;readonly limitMicros:number;readonly spentMicros:number;readonly remainingMicros:number;readonly status:"active"|"exhausted";readonly createdAt:string}
export interface InterventionRecord{readonly id:string;readonly workspaceId:string;readonly brandId:string;readonly actorType:"operator";readonly actorId:string;readonly action:InterventionAction;readonly targetType:string;readonly targetId:string;readonly reason:string;readonly at:string;readonly relatedFailureId?:string}
const stages=["brand-setup","hunter","research","generation","critic","publishing","metrics"]as const,retries=["safe","manual-review","blocked"]as const,costKinds=["model","search","tool","social"]as const,actions=["retry-requested","automation-disabled","content-withdrawn","configuration-corrected","safety-reviewed"]as const;
export function createOperationalFailure(input:{id:string;workspaceId:string;brandId:string;workflowId:string;stage:WorkflowStage;diagnosticCode:string;summary:string;retryDisposition:RetryDisposition;attempt:number;maxAttempts:number;occurredAt:string;traceId?:string}):OperationalFailure{const attempt=positive(input.attempt,"attempt"),maxAttempts=positive(input.maxAttempts,"maxAttempts");if(attempt>maxAttempts)throw new DomainValidationError("attempt cannot exceed maxAttempts");const out:OperationalFailure={id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),workflowId:text(input.workflowId,"workflowId",200),stage:one(input.stage,stages,"stage"),diagnosticCode:text(input.diagnosticCode,"diagnosticCode",160),summary:text(input.summary,"summary",500),retryDisposition:one(input.retryDisposition,retries,"retryDisposition"),attempt,maxAttempts,state:"failed",occurredAt:time(input.occurredAt,"occurredAt"),...(input.traceId?{traceId:text(input.traceId,"traceId",200)}:{})};return Object.freeze(out)}
export function requestSafeRetry(failure:OperationalFailure,input:{actorType:"operator";actorId:string;idempotencyKey:string;requestedAt:string}):RetryRequest{operator(input.actorType);if(failure.state!=="failed")throw new DomainValidationError("Failure is not in a retryable state");if(failure.retryDisposition!=="safe")throw new DomainValidationError("Failure is not safe to retry");if(failure.attempt>=failure.maxAttempts)throw new DomainValidationError("Retry attempts exhausted");const requestedAt=time(input.requestedAt,"requestedAt");if(Date.parse(requestedAt)<Date.parse(failure.occurredAt))throw new DomainValidationError("Retry cannot predate failure");const idempotencyKey=text(input.idempotencyKey,"idempotencyKey",200);return Object.freeze({id:`retry:${failure.id}:${idempotencyKey}`,workspaceId:failure.workspaceId,brandId:failure.brandId,workflowId:failure.workflowId,failureId:failure.id,attempt:failure.attempt+1,idempotencyKey,requestedBy:text(input.actorId,"actorId",200),requestedAt})}
export function createAutomationControl(input:{id:string;workspaceId:string;brandId:string;automationKey:string;stage:WorkflowStage;createdAt:string}):AutomationControl{return Object.freeze({id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),automationKey:text(input.automationKey,"automationKey",200),stage:one(input.stage,stages,"stage"),status:"enabled",version:1,createdAt:time(input.createdAt,"createdAt")})}
export function disableAutomation(control:AutomationControl,input:{actorType:"operator";actorId:string;reason:string;at:string;expectedVersion:number}):AutomationControl{operator(input.actorType);const expected=positive(input.expectedVersion,"expectedVersion");if(expected!==control.version)throw new ConcurrencyConflictError("Automation control version conflict");if(control.status==="disabled")throw new DomainValidationError("Automation is already disabled");const at=time(input.at,"at");if(Date.parse(at)<Date.parse(control.createdAt))throw new DomainValidationError("Disable action cannot predate automation control");return Object.freeze({...control,status:"disabled",version:control.version+1,disabledAt:at,disabledBy:text(input.actorId,"actorId",200),disabledReason:text(input.reason,"reason",500)})}
export function createCostEvent(input:{id:string;workspaceId:string;brandId:string;workflowId:string;kind:CostKind;provider:string;currency:string;costMicros:number;occurredAt:string}):CostEvent{return Object.freeze({id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),workflowId:text(input.workflowId,"workflowId",200),kind:one(input.kind,costKinds,"kind"),provider:text(input.provider,"provider",160),currency:currency(input.currency),costMicros:nonNegative(input.costMicros,"costMicros"),occurredAt:time(input.occurredAt,"occurredAt")})}
export function createWorkflowBudget(input:{id:string;workspaceId:string;brandId:string;workflowId:string;currency:string;limitMicros:number;createdAt:string}):WorkflowBudget{const limitMicros=positive(input.limitMicros,"limitMicros");return Object.freeze({id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),workflowId:text(input.workflowId,"workflowId",200),currency:currency(input.currency),limitMicros,spentMicros:0,remainingMicros:limitMicros,status:"active",createdAt:time(input.createdAt,"createdAt")})}
export function applyCostToBudget(budget:WorkflowBudget,event:CostEvent):WorkflowBudget{if(event.workspaceId!==budget.workspaceId||event.brandId!==budget.brandId||event.workflowId!==budget.workflowId||event.currency!==budget.currency)throw new DomainValidationError("Cost event is outside the workflow budget scope");const spentMicros=budget.spentMicros+event.costMicros;if(!Number.isSafeInteger(spentMicros)||spentMicros>budget.limitMicros)throw new DomainValidationError("Workflow budget exceeded");const remainingMicros=budget.limitMicros-spentMicros;return Object.freeze({...budget,spentMicros,remainingMicros,status:remainingMicros===0?"exhausted":"active"})}
export function recordIntervention(input:{id:string;workspaceId:string;brandId:string;actorType:"operator";actorId:string;action:InterventionAction;targetType:string;targetId:string;reason:string;at:string;relatedFailureId?:string}):InterventionRecord{operator(input.actorType);return Object.freeze({id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),actorType:"operator",actorId:text(input.actorId,"actorId",200),action:one(input.action,actions,"action"),targetType:text(input.targetType,"targetType",120),targetId:text(input.targetId,"targetId",200),reason:text(input.reason,"reason",500),at:time(input.at,"at"),...(input.relatedFailureId?{relatedFailureId:text(input.relatedFailureId,"relatedFailureId",200)}:{})})}
function operator(value:unknown){if(value!=="operator")throw new DomainValidationError("Operator authority is required")}
function text(value:unknown,field:string,max:number){if(typeof value!=="string"||!value.trim())throw new DomainValidationError(`${field} is required`);const v=value.trim();if(v.length>max)throw new DomainValidationError(`${field} is too long`);return v}
function time(value:unknown,field:string){const v=text(value,field,100),ms=Date.parse(v);if(Number.isNaN(ms))throw new DomainValidationError(`${field} must be a valid timestamp`);return new Date(ms).toISOString()}
function positive(value:unknown,field:string){if(!Number.isSafeInteger(value)||Number(value)<1)throw new DomainValidationError(`${field} must be a positive safe integer`);return Number(value)}
function nonNegative(value:unknown,field:string){if(!Number.isSafeInteger(value)||Number(value)<0)throw new DomainValidationError(`${field} must be a non-negative safe integer`);return Number(value)}
function currency(value:unknown){const v=text(value,"currency",3).toUpperCase();if(!/^[A-Z]{3}$/.test(v))throw new DomainValidationError("currency must be a 3-letter code");return v}
function one<const T extends string>(value:unknown,values:readonly T[],field:string):T{if(typeof value!=="string"||!values.includes(value as T))throw new DomainValidationError(`${field} is not supported`);return value as T}
