import { createHash } from "node:crypto";
import { DomainValidationError } from "./index";
import type { ContentApproval } from "./review";

export type PublishChannel="linkedin"|"instagram"|"facebook"|"manual";
export type ChannelAuthMethod="facebook-login"|"instagram-login"|"provider-native";
export type PublishCapability="publish-text"|"publish-image"|"publish-video"|"publish-carousel"|"publish-reel";
export type PublishContentType="text"|"image"|"video"|"carousel"|"reel";
export type PublishStatus="scheduled"|"dispatching"|"published"|"failed"|"unknown"|"manual-required"|"cancelled";
export type PublishLifecycleStatus="approved"|"publishing"|"processing"|"published"|"failed";
export type PublishMediaKind="image"|"video";
export interface PublishMediaItem{kind:PublishMediaKind;url:string}
export interface PublishOptions{instagram?:{shareToFeed?:boolean}}
export interface RenderedMediaApproval{id:string;workspaceId:string;brandId:string;assetId:string;contentVersionId:string;assetVersionId:string;mediaFingerprint:string;approvedAt:string}
export interface ChannelAccount{id:string;workspaceId:string;brandId:string;channel:PublishChannel;accountRef:string;displayName:string;credentialRef:string;authMethod?:ChannelAuthMethod;capabilities:PublishCapability[];status:"connected"|"reconnect-required"|"disabled";connectedAt:string}
export interface PublishCommand{id:string;workspaceId:string;brandId:string;campaignId:string;assetId:string;versionId:string;approvedAssetVersionId?:string;approvedMediaFingerprint?:string;lifecycleStatus?:PublishLifecycleStatus;version:number;approvalId:string;channelAccountId:string;channel:PublishChannel;accountRef:string;contentType:PublishContentType;mediaItems?:PublishMediaItem[];options?:PublishOptions;scheduledFor:string;status:PublishStatus;attemptCount:number;createdAt:string;lastAttemptAt?:string;metaContainerId?:string;providerPublishId?:string;failureReason?:string;publishedUrl?:string}
export interface PublishAttempt{id:string;commandId:string;versionId:string;idempotencyKey:string;attemptNumber:number;status:"dispatching"|"published"|"failed"|"unknown";startedAt:string;completedAt?:string;externalPostId?:string;providerCorrelationId?:string;failureCode?:string}
export interface PublishedPost{id:string;workspaceId:string;brandId:string;campaignId:string;assetId:string;versionId:string;publishCommandId:string;channel:string;accountRef:string;externalPostId:string;publishedAt:string;publishedUrl?:string}

export function connectChannelAccount(input:Omit<ChannelAccount,"status">):ChannelAccount{const channel=one(input.channel,["linkedin","instagram","facebook","manual"],"channel"),authMethod=input.authMethod===undefined?undefined:one(input.authMethod,["facebook-login","instagram-login","provider-native"],"authMethod");if(channel==="facebook"&&authMethod!=="facebook-login")throw new DomainValidationError("Facebook publishing requires Facebook Login");if(channel==="instagram"&&authMethod==="provider-native")throw new DomainValidationError("Instagram publishing requires a Meta login method");return{id:text(input.id,"id",200),workspaceId:text(input.workspaceId,"workspaceId",200),brandId:text(input.brandId,"brandId",200),channel,accountRef:text(input.accountRef,"accountRef",300),displayName:text(input.displayName,"displayName",300),credentialRef:text(input.credentialRef,"credentialRef",500),...(authMethod?{authMethod}:{}),capabilities:unique(input.capabilities),status:"connected",connectedAt:time(input.connectedAt,"connectedAt")}}
export function createPublishCommand(input:{id:string;approval:ContentApproval;currentVersionId:string;channelAccount:ChannelAccount;contentType:PublishContentType;mediaItems?:PublishMediaItem[];options?:PublishOptions;scheduledFor:string;createdAt:string}):PublishCommand{const a=input.approval,c=input.channelAccount;if(text(input.currentVersionId,"currentVersionId",200)!==a.versionId)throw new DomainValidationError("Publishing requires the current approved version");if(a.workspaceId!==c.workspaceId||a.brandId!==c.brandId)throw new DomainValidationError("Channel Account is outside approval scope");if(a.destination.channel!==c.channel||a.destination.accountRef!==c.accountRef)throw new DomainValidationError("Approval destination does not match Channel Account");const contentType=one(input.contentType,["text","image","video","carousel","reel"],"contentType"),mediaItems=normalizeMediaItems(input.mediaItems),options=normalizeOptions(input.options);validateMediaShape(c.channel,contentType,mediaItems);const cap=capabilityFor(contentType),scheduledFor=time(input.scheduledFor,"scheduledFor"),createdAt=time(input.createdAt,"createdAt");if(Date.parse(scheduledFor)<Date.parse(createdAt))throw new DomainValidationError("scheduledFor cannot be in the past");const automatic=c.status==="connected"&&c.channel!=="manual"&&c.capabilities.includes(cap);return{id:text(input.id,"id",200),workspaceId:a.workspaceId,brandId:a.brandId,campaignId:a.campaignId,assetId:a.assetId,versionId:a.versionId,approvedAssetVersionId:a.versionId,approvedMediaFingerprint:mediaFingerprint(mediaItems),lifecycleStatus:"approved",version:a.version,approvalId:a.id,channelAccountId:c.id,channel:c.channel,accountRef:c.accountRef,contentType,mediaItems,options,scheduledFor,status:automatic?"scheduled":"manual-required",attemptCount:0,createdAt}}
export function beginPublishAttempt(input:{id:string;command:PublishCommand;startedAt:string}):PublishAttempt{if(input.command.status!=="scheduled"&&input.command.status!=="failed")throw new DomainValidationError("Publish Command is not dispatchable");if(input.command.attemptCount>=3)throw new DomainValidationError("Publish retry limit reached");return{id:text(input.id,"id",200),commandId:input.command.id,versionId:input.command.versionId,idempotencyKey:`${input.command.id}:${input.command.versionId}:${input.command.accountRef}`,attemptNumber:input.command.attemptCount+1,status:"dispatching",startedAt:time(input.startedAt,"startedAt")}}
export function reconcilePublishAttempt(input:{attempt:PublishAttempt;outcome:"published"|"failed"|"unknown";checkedAt:string;externalPostId?:string;providerCorrelationId?:string;failureCode?:string}):PublishAttempt{if(input.attempt.status==="published")throw new DomainValidationError("Published attempt is terminal");const status=one(input.outcome,["published","failed","unknown"],"outcome");if(status==="published"&&!input.externalPostId)throw new DomainValidationError("Published outcome requires externalPostId");return{...input.attempt,status,completedAt:time(input.checkedAt,"checkedAt"),...(input.externalPostId?{externalPostId:text(input.externalPostId,"externalPostId",500)}:{}),...(input.providerCorrelationId?{providerCorrelationId:text(input.providerCorrelationId,"providerCorrelationId",500)}:{}),...(input.failureCode?{failureCode:text(input.failureCode,"failureCode",200)}:{})}}
export function applyPublishAttempt(command:PublishCommand,attempt:PublishAttempt):PublishCommand{if(attempt.commandId!==command.id||attempt.versionId!==command.versionId)throw new DomainValidationError("Publish Attempt does not match command");if(attempt.attemptNumber!==command.attemptCount+1&&attempt.attemptNumber!==command.attemptCount)throw new DomainValidationError("Publish Attempt sequence is invalid");const lifecycleStatus:PublishLifecycleStatus=attempt.status==="dispatching"?"publishing":attempt.status==="published"?"published":attempt.status==="failed"?"failed":command.lifecycleStatus??"publishing";return{...command,status:attempt.status,lifecycleStatus,attemptCount:attempt.attemptNumber,lastAttemptAt:attempt.completedAt??attempt.startedAt,...(attempt.providerCorrelationId?{metaContainerId:attempt.providerCorrelationId}:{}),...(attempt.externalPostId?{providerPublishId:attempt.externalPostId}:{}),...(attempt.failureCode?{failureReason:attempt.failureCode}:{})}}
export function createPublishedPost(input:{id:string;command:PublishCommand;attempt:PublishAttempt}):PublishedPost{const {command,attempt}=input;if(command.status!=="published"||attempt.status!=="published"||attempt.commandId!==command.id||attempt.versionId!==command.versionId||!attempt.externalPostId||!attempt.completedAt)throw new DomainValidationError("Published Post requires a matching successful attempt");return{id:text(input.id,"id",200),workspaceId:command.workspaceId,brandId:command.brandId,campaignId:command.campaignId,assetId:command.assetId,versionId:command.versionId,publishCommandId:command.id,channel:command.channel,accountRef:command.accountRef,externalPostId:attempt.externalPostId,publishedAt:attempt.completedAt}}
export function assertApprovedMedia(command:PublishCommand,versionId:string,mediaItems:PublishMediaItem[]):void{if((command.approvedAssetVersionId??command.versionId)!==text(versionId,"approvedAssetVersionId",200))throw new DomainValidationError("Publishing media is outside the approved asset version");const expected=command.approvedMediaFingerprint??mediaFingerprint(command.mediaItems??[]);if(mediaFingerprint(normalizeMediaItems(mediaItems))!==expected)throw new DomainValidationError("Publishing media does not match the approved asset version")}
export function markPublishProcessing(command:PublishCommand,input:{containerId:string;at:string}):PublishCommand{const state=command.lifecycleStatus??"approved";if(state!=="approved"&&state!=="publishing")throw new DomainValidationError("Publish verification cannot enter Processing from its current state");return{...command,lifecycleStatus:"processing",status:"dispatching",metaContainerId:text(input.containerId,"containerId",500),lastAttemptAt:time(input.at,"at")}}
export function verifyPublishOutcome(command:PublishCommand,input:{outcome:"published"|"failed";at:string;publishId?:string;publishedUrl?:string;failureReason?:string}):PublishCommand{if((command.lifecycleStatus??"approved")!=="processing")throw new DomainValidationError("Publish verification requires Processing state");const at=time(input.at,"at");if(input.outcome==="failed")return{...command,lifecycleStatus:"failed",status:"failed",failureReason:text(input.failureReason,"failureReason",1000),lastAttemptAt:at};const providerPublishId=text(input.publishId,"publishId",500),publishedUrl=publicHttps(input.publishedUrl,"publishedUrl");return{...command,lifecycleStatus:"published",status:"published",providerPublishId,publishedUrl,lastAttemptAt:at}}
export function retryPublishCommand(command:PublishCommand,at:string):PublishCommand{if(command.status!=="failed")throw new DomainValidationError("Only failed publishing can be retried; unknown outcomes require reconciliation");if(command.attemptCount>=3)throw new DomainValidationError("Publish retry limit reached");return{...command,status:"scheduled",lifecycleStatus:"approved",failureReason:undefined,lastAttemptAt:time(at,"lastAttemptAt")}}
export function cancelPublishCommand(command:PublishCommand):PublishCommand{if(command.status!=="scheduled"&&command.status!=="manual-required")throw new DomainValidationError("Only pending publishing can be cancelled");return{...command,status:"cancelled"}}
export function createVerifiedPublishCommand(input:{id:string;approval:ContentApproval;renderedApproval:RenderedMediaApproval;currentVersionId:string;channelAccount:ChannelAccount;contentType:PublishContentType;mediaItems?:PublishMediaItem[];options?:PublishOptions;scheduledFor:string;createdAt:string}):PublishCommand{const rendered=input.renderedApproval;if(rendered.workspaceId!==input.approval.workspaceId||rendered.brandId!==input.approval.brandId||rendered.assetId!==input.approval.assetId||rendered.contentVersionId!==input.approval.versionId)throw new DomainValidationError("Rendered media approval is outside the approved Content Version");const fingerprint=text(rendered.mediaFingerprint,"renderedApproval.mediaFingerprint",64);if(!/^[a-f0-9]{64}$/.test(fingerprint))throw new DomainValidationError("Rendered media approval fingerprint is invalid");return{...createPublishCommand(input),approvedAssetVersionId:text(rendered.assetVersionId,"renderedApproval.assetVersionId",200),approvedMediaFingerprint:fingerprint}}
function capabilityFor(contentType:PublishContentType):PublishCapability{return contentType==="reel"?"publish-reel":`publish-${contentType}` as PublishCapability}
function validateMediaShape(channel:PublishChannel,contentType:PublishContentType,items:PublishMediaItem[]){if(channel==="instagram"){if(contentType==="image"&&(items.length!==1||items[0]?.kind!=="image"))throw new DomainValidationError("Instagram image publishing requires exactly one image");if(contentType==="reel"&&(items.length!==1||items[0]?.kind!=="video"))throw new DomainValidationError("Instagram Reel publishing requires exactly one video");if(contentType==="carousel"&&(items.length<2||items.length>10||items.some(item=>item.kind!=="image")))throw new DomainValidationError("Instagram carousel publishing requires 2 to 10 images")}if(channel==="facebook"&&contentType==="image"&&(items.length!==1||items[0]?.kind!=="image"))throw new DomainValidationError("Facebook image publishing requires exactly one image")}
function normalizeMediaItems(value:unknown):PublishMediaItem[]{if(value===undefined)return[];if(!Array.isArray(value))throw new DomainValidationError("mediaItems must be a list");return value.map((raw,index)=>{if(!raw||typeof raw!=="object")throw new DomainValidationError(`mediaItems[${index}] must be an object`);const item=raw as Record<string,unknown>,kind=one(item.kind,["image","video"],`mediaItems[${index}].kind`),url=text(item.url,`mediaItems[${index}].url`,2048);let parsed:URL;try{parsed=new URL(url)}catch{throw new DomainValidationError(`mediaItems[${index}].url must be a valid URL`)}if(parsed.protocol!=="https:")throw new DomainValidationError(`mediaItems[${index}].url must use HTTPS`);if(parsed.username||parsed.password)throw new DomainValidationError(`mediaItems[${index}].url must not contain credentials`);return{kind,url:parsed.toString()}})}
function normalizeOptions(value:unknown):PublishOptions{if(value===undefined)return{};if(!value||typeof value!=="object"||Array.isArray(value))throw new DomainValidationError("options must be an object");const raw=(value as Record<string,unknown>).instagram;if(raw===undefined)return{};if(!raw||typeof raw!=="object"||Array.isArray(raw))throw new DomainValidationError("options.instagram must be an object");const share=(raw as Record<string,unknown>).shareToFeed;if(share!==undefined&&typeof share!=="boolean")throw new DomainValidationError("options.instagram.shareToFeed must be boolean");return{instagram:{...(share===undefined?{}:{shareToFeed:share})}}}
function text(v:unknown,f:string,max:number){if(typeof v!=="string"||!v.trim())throw new DomainValidationError(`${f} is required`);const n=v.trim();if(n.length>max)throw new DomainValidationError(`${f} is too long`);return n}
function time(v:unknown,f:string){const n=text(v,f,80);if(Number.isNaN(Date.parse(n)))throw new DomainValidationError(`${f} must be a valid timestamp`);return n}
function one<const T extends string>(v:unknown,values:readonly T[],f:string):T{if(typeof v!=="string"||!values.includes(v as T))throw new DomainValidationError(`${f} is not supported`);return v as T}
function unique(v:unknown):PublishCapability[]{if(!Array.isArray(v))throw new DomainValidationError("capabilities must be a list");const values=v.map(x=>one(x,["publish-text","publish-image","publish-video","publish-carousel","publish-reel"],"capability"));if(new Set(values).size!==values.length)throw new DomainValidationError("capabilities must not contain duplicates");return values}
function mediaFingerprint(items:PublishMediaItem[]):string{return createHash("sha256").update(JSON.stringify(items.map(item=>({kind:item.kind,url:item.url})))).digest("hex")}
function publicHttps(value:unknown,field:string):string{const normalized=text(value,field,2048);let url:URL;try{url=new URL(normalized)}catch{throw new DomainValidationError(`${field} must be a valid URL`)}if(url.protocol!=="https:"||url.username||url.password)throw new DomainValidationError(`${field} must use HTTPS without credentials`);return url.toString()}
