import { describe, expect, it } from "vitest";
import { applyPublishAttempt, assertApprovedMedia, beginPublishAttempt, cancelPublishCommand, connectChannelAccount, createPublishedPost, createPublishCommand, createVerifiedPublishCommand, markPublishProcessing, reconcilePublishAttempt, retryPublishCommand, verifyPublishOutcome } from "./publishing";
import type { ContentApproval } from "./review";

const approval:ContentApproval={id:"approval-1",reviewId:"review-1",approverAccountId:"human-1",workspaceId:"ws-1",brandId:"brand-1",campaignId:"campaign-1",assetId:"asset-1",versionId:"version-2",version:2,destination:{channel:"linkedin",accountRef:"page-1"},approvedAt:"2026-08-13T10:00:00Z"};

describe("VS-07 publishing domain",()=>{
  it("keeps Meta authentication explicit for Facebook and Instagram",()=>{expect(connectChannelAccount({id:"fb",workspaceId:"ws-1",brandId:"brand-1",channel:"facebook",accountRef:"123",displayName:"Page",credentialRef:"vault://fb",authMethod:"facebook-login",capabilities:["publish-text","publish-image"],connectedAt:"2026-08-13T10:01:00Z"})).toMatchObject({channel:"facebook",authMethod:"facebook-login"});expect(()=>connectChannelAccount({id:"fb",workspaceId:"ws-1",brandId:"brand-1",channel:"facebook",accountRef:"123",displayName:"Page",credentialRef:"vault://fb",authMethod:"instagram-login",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"})).toThrow(/Facebook Login/) });
  it("stores only an opaque credential reference and explicit capabilities",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});expect(account).toMatchObject({credentialRef:"vault://channels/1",status:"connected"});expect(account).not.toHaveProperty("accessToken")});
  it("schedules only the exact current approved version and destination",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});expect(()=>createPublishCommand({id:"publish-1",approval,currentVersionId:"version-3",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"})).toThrow(/current approved version/i);expect(()=>createPublishCommand({id:"publish-1",approval:{...approval,destination:{channel:"linkedin",accountRef:"other"}},currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"})).toThrow(/destination/i)});
  it("degrades unsupported capability to manual-required",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"video",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});expect(command.status).toBe("manual-required")});
  it("uses stable idempotency and keeps timeouts unknown until reconciliation",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});const attempt=beginPublishAttempt({id:"attempt-1",command,startedAt:"2026-08-14T10:00:00Z"});expect(attempt.idempotencyKey).toBe("publish-1:version-2:page-1");const unknown=reconcilePublishAttempt({attempt,outcome:"unknown",checkedAt:"2026-08-14T10:01:00Z"});expect(unknown.status).toBe("unknown");expect(()=>retryPublishCommand({...command,status:"unknown",attemptCount:1},"2026-08-14T10:02:00Z")).toThrow(/reconciliation/i);expect(()=>retryPublishCommand({...command,status:"failed",attemptCount:3},"2026-08-14T10:02:00Z")).toThrow(/retry limit/i)});
  it("records attempt sequence and creates immutable published identity",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-text"],connectedAt:"2026-08-13T10:01:00Z"});const command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});const attempt=reconcilePublishAttempt({attempt:beginPublishAttempt({id:"attempt-1",command,startedAt:"2026-08-14T10:00:00Z"}),outcome:"published",externalPostId:"urn:li:share:123",checkedAt:"2026-08-14T10:01:00Z"});const completed=applyPublishAttempt(command,attempt);expect(completed).toMatchObject({status:"published",attemptCount:1});expect(createPublishedPost({id:"post-1",command:completed,attempt})).toMatchObject({versionId:"version-2",externalPostId:"urn:li:share:123"})});
  it("cancels only commands that have not started dispatch",()=>{const pending={id:"p",workspaceId:"w",brandId:"b",campaignId:"c",assetId:"a",versionId:"v",version:1,approvalId:"q",channelAccountId:"ca",channel:"manual",accountRef:"manual",contentType:"text",scheduledFor:"2026-08-14T10:00:00Z",status:"manual-required",attemptCount:0,createdAt:"2026-08-13T10:00:00Z"}as const;expect(cancelPublishCommand(pending).status).toBe("cancelled");expect(()=>cancelPublishCommand({...pending,status:"published"})).toThrow(/pending/i)});
});

describe("VS-77 verified publishing",()=>{it("binds approved media and verifies Processing before publication",()=>{const media=[{kind:"image" as const,url:"https://cdn.example.test/approved.png"}],account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-image"],connectedAt:"2026-08-13T10:01:00Z"}),command=createPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"image",mediaItems:media,scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z"});expect(command).toMatchObject({approvedAssetVersionId:"version-2",lifecycleStatus:"approved",approvedMediaFingerprint:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(()=>assertApprovedMedia(command,"version-3",media)).toThrow(/approved asset version/i);expect(()=>assertApprovedMedia(command,"version-2",[{kind:"image",url:"https://cdn.example.test/changed.png"}])).toThrow(/does not match/i);const processing=markPublishProcessing(command,{containerId:"container-1",at:"2026-08-14T10:01:00Z"});expect(processing).toMatchObject({lifecycleStatus:"processing",metaContainerId:"container-1"});expect(verifyPublishOutcome(processing,{outcome:"published",publishId:"media-1",publishedUrl:"https://www.instagram.com/p/media-1/",at:"2026-08-14T10:02:00Z"})).toMatchObject({lifecycleStatus:"published",providerPublishId:"media-1"});expect(()=>verifyPublishOutcome(command,{outcome:"published",publishId:"media-1",publishedUrl:"https://example.test/post",at:"2026-08-14T10:02:00Z"})).toThrow(/Processing/i)})});

describe("VS-77 rendered approval binding",()=>{it("rejects a rendered approval outside the approved Content Version",()=>{const account=connectChannelAccount({id:"channel-1",workspaceId:"ws-1",brandId:"brand-1",channel:"linkedin",accountRef:"page-1",displayName:"Kairo",credentialRef:"vault://channels/1",capabilities:["publish-image"],connectedAt:"2026-08-13T10:01:00Z"});expect(()=>createVerifiedPublishCommand({id:"publish-1",approval,currentVersionId:"version-2",channelAccount:account,contentType:"image",mediaItems:[{kind:"image",url:"https://cdn.example.test/approved.png"}],scheduledFor:"2026-08-14T10:00:00Z",createdAt:"2026-08-13T10:02:00Z",renderedApproval:{id:"rendered-1",workspaceId:"ws-1",brandId:"brand-1",assetId:"asset-1",contentVersionId:"other",assetVersionId:"carousel-v7",mediaFingerprint:"a".repeat(64),approvedAt:"2026-08-13T10:01:00Z"}})).toThrow(/approved Content Version/i)})});
