import { DomainValidationError } from "./index";
import type { NormalizedMetric } from "./analytics";
import type { ChannelAccount, PublishCommand, PublishedPost } from "./publishing";

export interface FinishedMediaReview{workspaceId:string;brandId:string;campaignId:string;assetId:string;contentType:"image"|"carousel"|"reel"|"video"|"text";title:string;itemCount:number;previewUrls:string[];assetVersionId?:string;approved:boolean;qualityStatus:"unchecked"|"passed"|"blocked";blockingIssues:number}
export interface SimplePublishFlowSource{media:FinishedMediaReview;destination?:ChannelAccount;command?:PublishCommand;publishedPost?:PublishedPost;metrics:NormalizedMetric[];links:{mediaEditor:string;approvalHistory:string;publishingDetails:string;performanceDetails:string}}
export interface SimplePublishFlowRepository{read(accountId:string,brandId:string,assetId:string):Promise<SimplePublishFlowSource|null>}

export class SimplePublishFlowService{constructor(private repo:SimplePublishFlowRepository){}async get(accountId:string,brandId:string,assetId:string){const source=await this.repo.read(required(accountId,"accountId"),required(brandId,"brandId"),required(assetId,"assetId"));if(!source)throw new Error("Content Asset not found");return projectSimplePublishFlow(source)}}

export function projectSimplePublishFlow(source:SimplePublishFlowSource){const media=source.media;validateMedia(media);const destination=source.destination;if(destination&&(destination.workspaceId!==media.workspaceId||destination.brandId!==media.brandId))throw new DomainValidationError("Destination is outside media scope");const command=source.command;if(command&&(command.workspaceId!==media.workspaceId||command.brandId!==media.brandId||command.campaignId!==media.campaignId||command.assetId!==media.assetId))throw new DomainValidationError("Publish Command is outside media scope");const post=source.publishedPost;if(post&&(post.workspaceId!==media.workspaceId||post.brandId!==media.brandId||post.assetId!==media.assetId||post.publishCommandId!==command?.id))throw new DomainValidationError("Published Post is outside media scope");if(source.metrics.some(metric=>metric.workspaceId!==media.workspaceId||metric.brandId!==media.brandId||metric.publishedPostId!==post?.id))throw new DomainValidationError("Performance metric is outside published media scope");const publish=readiness(media,destination,command),result=publishResult(command,post),metrics=source.metrics.map(metric=>({name:metric.name,status:metric.status,...(metric.value===undefined?{}:{value:metric.value}),capturedAt:metric.capturedAt,...(metric.reason?{reason:metric.reason}:{})}));return{brandId:media.brandId,campaignId:media.campaignId,assetId:media.assetId,review:{status:media.approved&&media.qualityStatus==="passed"?"ready" as const:"needs-review" as const,contentType:media.contentType,title:media.title,itemCount:media.itemCount,...(media.assetVersionId?{approvedAssetVersionId:media.assetVersionId}:{}),previewUrls:[...media.previewUrls],quality:{status:media.qualityStatus,blockingIssues:media.blockingIssues}},publish,result,performance:{status:post&&metrics.length?"available" as const:"waiting" as const,metrics},advancedLinks:[link("media-editor","Edit media",source.links.mediaEditor),link("approval-history","Approval history",source.links.approvalHistory),link("publishing-details","Publishing details",source.links.publishingDetails),link("performance-details","Performance details",source.links.performanceDetails)]}}
function readiness(media:FinishedMediaReview,destination:ChannelAccount|undefined,command:PublishCommand|undefined){if(!media.approved||media.qualityStatus!=="passed")return{status:"needs-review" as const,reason:media.qualityStatus==="blocked"?"Resolve blocking media quality issues and approve again":"Approve the finished media"};if(!destination)return{status:"needs-destination" as const,reason:"Choose a publishing destination"};const target={channel:destination.channel,accountRef:destination.accountRef,displayName:destination.displayName,health:destination.status};if(destination.status!=="connected")return{status:"needs-destination" as const,destination:target,reason:"Reconnect or choose another destination"};if(command)return{status:"scheduled" as const,destination:target,scheduledFor:command.scheduledFor};return{status:"ready" as const,destination:target}}
function publishResult(command:PublishCommand|undefined,post:PublishedPost|undefined){if(!command)return{status:"not-started" as const};const status=command.lifecycleStatus??(command.status==="dispatching"?"publishing":command.status==="published"?"published":command.status==="failed"?"failed":"approved");return{status,publishCommandId:command.id,...(command.providerPublishId?{publishId:command.providerPublishId}:post?{publishId:post.externalPostId}:{}),...(command.publishedUrl?{publishedUrl:command.publishedUrl}:post?.publishedUrl?{publishedUrl:post.publishedUrl}:{}),...(command.failureReason?{failureReason:command.failureReason}:{}),...(post?{publishedAt:post.publishedAt}:{})}}
function validateMedia(media:FinishedMediaReview){required(media.workspaceId,"workspaceId");required(media.brandId,"brandId");required(media.campaignId,"campaignId");required(media.assetId,"assetId");required(media.title,"title");if(!Number.isInteger(media.itemCount)||media.itemCount<0||!Number.isInteger(media.blockingIssues)||media.blockingIssues<0)throw new DomainValidationError("Finished media counts are invalid");if(media.qualityStatus==="passed"&&media.blockingIssues!==0)throw new DomainValidationError("Passed media cannot have blocking issues");for(const value of media.previewUrls)https(value,"previewUrl")}
function link(key:"media-editor"|"approval-history"|"publishing-details"|"performance-details",label:string,href:string){return{key,label,href:internal(href)}}
function internal(value:string){const path=required(value,"advanced link");if(!path.startsWith("/")||path.startsWith("//"))throw new DomainValidationError("Advanced link must be an internal path");return path}
function https(value:string,field:string){let url:URL;try{url=new URL(value)}catch{throw new DomainValidationError(`${field} must be a URL`)}if(url.protocol!=="https:")throw new DomainValidationError(`${field} must use HTTPS`)}
function required(value:unknown,field:string){if(typeof value!=="string"||!value.trim()||value.trim().length>500)throw new DomainValidationError(`${field} is required`);return value.trim()}
