import type { Pool, PoolClient } from "pg";
import { ConcurrencyConflictError, ResourceNotFoundError } from "@kairo/domain";
import type { Campaign, ContentAsset, ContentVersion } from "@kairo/domain/campaign";
import type { CampaignDetail, CampaignRepository } from "@kairo/domain/campaign-service";

export class PgCampaignRepository implements CampaignRepository {
  constructor(private readonly pool: Pool) {}
  async saveCampaign(accountId: string, c: Campaign): Promise<Campaign> { const client=await this.pool.connect(); try { const ws=await scope(client,accountId,c.brandId); if(ws!==c.workspaceId) throw new ResourceNotFoundError("Brand not found"); await client.query(`insert into campaigns(id,workspace_id,brand_id,idea_id,research_id,angle_id,name,objective,supporting_claim_ids,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11)`,[c.id,c.workspaceId,c.brandId,c.ideaId,c.researchId,c.angleId,c.name,c.objective,JSON.stringify(c.supportingClaimIds),c.status,c.createdAt]); return c; } finally { client.release(); } }
  async listCampaigns(accountId:string,brandId:string):Promise<Campaign[]>{const client=await this.pool.connect();try{const ws=await scope(client,accountId,brandId);const r=await client.query<CampaignRow>(campaignSelect+` where workspace_id=$1 and brand_id=$2 order by created_at desc,id`,[ws,brandId]);return r.rows.map(toCampaign);}finally{client.release();}}
  async getCampaign(accountId:string,brandId:string,id:string):Promise<CampaignDetail|null>{const client=await this.pool.connect();try{const ws=await scope(client,accountId,brandId);return loadDetail(client,ws,brandId,id);}finally{client.release();}}
  async saveAssetWithVersion(accountId:string,a:ContentAsset,v:ContentVersion):Promise<CampaignDetail>{const client=await this.pool.connect();try{await client.query("begin");const ws=await scope(client,accountId,a.brandId);const campaign=await loadDetail(client,ws,a.brandId,a.campaignId);if(!campaign)throw new ResourceNotFoundError("Campaign not found");await client.query(`insert into content_assets(id,workspace_id,brand_id,campaign_id,channel,format,audience,topic,hook_type,cta,supporting_claim_ids,current_version,status,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14)`,[a.id,ws,a.brandId,a.campaignId,a.channel,a.format,a.audience,a.topic,a.hookType,a.cta,JSON.stringify(a.supportingClaimIds),a.currentVersion,a.status,a.createdAt]);await insertVersion(client,v);await client.query("commit");return (await loadDetail(client,ws,a.brandId,a.campaignId))!;}catch(e){await rollback(client);throw e;}finally{client.release();}}
  async appendVersion(accountId:string,brandId:string,campaignId:string,assetId:string,expectedVersion:number,build:(a:ContentAsset,p:ContentVersion)=>ContentVersion):Promise<CampaignDetail>{const client=await this.pool.connect();try{await client.query("begin");const ws=await scope(client,accountId,brandId);const ar=await client.query<AssetRow>(assetSelect+` where workspace_id=$1 and brand_id=$2 and campaign_id=$3 and id=$4 for update`,[ws,brandId,campaignId,assetId]);const row=ar.rows[0];if(!row)throw new ResourceNotFoundError("Content Asset not found");if(row.current_version!==expectedVersion)throw new ConcurrencyConflictError("Content Version is stale");const vr=await client.query<VersionRow>(versionSelect+` where asset_id=$1 and version=$2`,[assetId,expectedVersion]);if(!vr.rows[0])throw new ResourceNotFoundError("Content Version not found");const next=build(toAsset(row),toVersion(vr.rows[0]));await insertVersion(client,next);await client.query(`update content_assets set current_version=$1 where id=$2`,[next.version,assetId]);await client.query("commit");return (await loadDetail(client,ws,brandId,campaignId))!;}catch(e){await rollback(client);throw e;}finally{client.release();}}
}
type CampaignRow={id:string;workspace_id:string;brand_id:string;idea_id:string;research_id:string;angle_id:string;name:string;objective:string;supporting_claim_ids:string[];status:"draft";created_at:Date|string};
type AssetRow={id:string;workspace_id:string;brand_id:string;campaign_id:string;channel:ContentAsset["channel"];format:string;audience:string;topic:string;hook_type:string;cta:string;supporting_claim_ids:string[];current_version:number;status:"draft";created_at:Date|string};
type VersionRow={id:string;workspace_id:string;brand_id:string;campaign_id:string;asset_id:string;version:number;parent_version_id:string|null;content:string;supporting_claim_ids:string[];actor:ContentVersion["actor"];action:ContentVersion["action"];library_asset_refs:NonNullable<ContentVersion["libraryAssetRefs"]>;provenance:ContentVersion["provenance"]|null;created_at:Date|string};
const campaignSelect=`select id,workspace_id,brand_id,idea_id,research_id,angle_id,name,objective,supporting_claim_ids,status,created_at from campaigns`;
const assetSelect=`select id,workspace_id,brand_id,campaign_id,channel,format,audience,topic,hook_type,cta,supporting_claim_ids,current_version,status,created_at from content_assets`;
const versionSelect=`select id,workspace_id,brand_id,campaign_id,asset_id,version,parent_version_id,content,supporting_claim_ids,actor,action,library_asset_refs,provenance,created_at from content_versions`;
async function loadDetail(c:PoolClient,ws:string,b:string,id:string):Promise<CampaignDetail|null>{const cr=await c.query<CampaignRow>(campaignSelect+` where workspace_id=$1 and brand_id=$2 and id=$3`,[ws,b,id]);if(!cr.rows[0])return null;const ar=await c.query<AssetRow>(assetSelect+` where campaign_id=$1 order by created_at,id`,[id]);const assets=[];for(const row of ar.rows){const vr=await c.query<VersionRow>(versionSelect+` where asset_id=$1 order by version`,[row.id]);assets.push({asset:toAsset(row),versions:vr.rows.map(toVersion)});}return{campaign:toCampaign(cr.rows[0]),assets};}
async function insertVersion(c:PoolClient,v:ContentVersion){await c.query(`insert into content_versions(id,workspace_id,brand_id,campaign_id,asset_id,version,parent_version_id,content,supporting_claim_ids,actor,action,library_asset_refs,provenance,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12::jsonb,$13::jsonb,$14)`,[v.id,v.workspaceId,v.brandId,v.campaignId,v.assetId,v.version,v.parentVersionId,v.content,JSON.stringify(v.supportingClaimIds),v.actor,v.action,JSON.stringify(v.libraryAssetRefs??[]),v.provenance?JSON.stringify(v.provenance):null,v.createdAt]);}
function toCampaign(r:CampaignRow):Campaign{return{id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,ideaId:r.idea_id,researchId:r.research_id,angleId:r.angle_id,name:r.name,objective:r.objective,supportingClaimIds:r.supporting_claim_ids,status:r.status,createdAt:iso(r.created_at)}}
function toAsset(r:AssetRow):ContentAsset{return{id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,campaignId:r.campaign_id,channel:r.channel,format:r.format,audience:r.audience,topic:r.topic,hookType:r.hook_type,cta:r.cta,supportingClaimIds:r.supporting_claim_ids,currentVersion:r.current_version,status:r.status,createdAt:iso(r.created_at)}}
function toVersion(r:VersionRow):ContentVersion{return{id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,campaignId:r.campaign_id,assetId:r.asset_id,version:r.version,parentVersionId:r.parent_version_id,content:r.content,supportingClaimIds:r.supporting_claim_ids,actor:r.actor,action:r.action,createdAt:iso(r.created_at),libraryAssetRefs:r.library_asset_refs??[],...(r.provenance?{provenance:r.provenance}:{})}}
async function scope(c:PoolClient,a:string,b:string){const r=await c.query<{workspace_id:string}>(`select b.workspace_id from brands b join workspace_memberships m on m.workspace_id=b.workspace_id where m.account_id=$1 and m.active=true and b.id=$2`,[a,b]);if(!r.rows[0])throw new ResourceNotFoundError("Brand not found");return r.rows[0].workspace_id;}
function iso(v:Date|string){return v instanceof Date?v.toISOString():new Date(v).toISOString()} async function rollback(c:PoolClient){try{await c.query("rollback")}catch{}}
