import type{FastifyInstance,FastifyReply,FastifyRequest}from"fastify";
import{DomainValidationError,KairoService,type KairoRepository}from"@kairo/domain";
import type{CarouselProject}from"@kairo/domain/carousel-project";
import type{IdentityVerifier}from"./auth";
import{PgCarouselStudioStore,type RenderedVersionInput}from"./carousel-studio-postgres";
import type{CarouselRenderService}from"./carousel-render-service";

type Scope={brandId:string;campaignId:string;assetId:string};
export function registerCarouselStudioRoutes(app:FastifyInstance,deps:{coreStore:KairoRepository;identityVerifier:IdentityVerifier;store:PgCarouselStudioStore;renderer?:CarouselRenderService}){const core=new KairoService(deps.coreStore);
 app.get<{Params:Scope}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.getReview(account.id,request.params.brandId,request.params.campaignId,request.params.assetId)});
 app.post<{Params:Scope}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/bootstrap",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return reply.status(201).send(await deps.store.bootstrap(account.id,request.params.brandId,request.params.campaignId,request.params.assetId))});
 app.post<{Params:Scope;Body:{contentVersionId:string;project:CarouselProject;templateId:string;style?:Record<string,unknown>}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return reply.status(201).send(await deps.store.upsert(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,request.body))});
 app.patch<{Params:Scope&{slideId:string};Body:{expectedAssetVersion:number;headline:string;body:string}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/slides/:slideId/text",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.editText(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,request.params.slideId,version(request.body?.expectedAssetVersion),request.body)});
 app.patch<{Params:Scope&{slideId:string};Body:{expectedAssetVersion:number;imageAssetId:string|null}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/slides/:slideId/image",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.replaceImage(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,request.params.slideId,version(request.body?.expectedAssetVersion),request.body.imageAssetId)});
 app.post<{Params:Scope;Body:{expectedAssetVersion:number;slideIds:string[]}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/slides/reorder",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.reorder(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,version(request.body?.expectedAssetVersion),request.body?.slideIds??[])});
 app.patch<{Params:Scope;Body:{expectedAssetVersion:number;slideIds:string[]}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/slides/reorder",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.reorder(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,version(request.body?.expectedAssetVersion),request.body?.slideIds??[])});
 app.post<{Params:Scope&{slideId:string};Body:{expectedAssetVersion:number;instruction?:string}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/slides/:slideId/regenerate",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return reply.status(202).send(await deps.store.requestRegeneration(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,request.params.slideId,version(request.body?.expectedAssetVersion),request.body?.instruction))});
 app.patch<{Params:Scope;Body:{expectedAssetVersion:number;templateId:string;style:Record<string,unknown>}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/style",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.changeStyle(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,version(request.body?.expectedAssetVersion),request.body)});
 app.post<{Params:Scope;Body:{expectedAssetVersion:number;templateId:string;style?:Record<string,unknown>;styleId?:string}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/style",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.changeStyle(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,version(request.body?.expectedAssetVersion),{templateId:request.body.templateId,style:request.body.style??{styleId:request.body.styleId??"default"}})});
 app.post<{Params:Scope;Body:{expectedAssetVersion:number;renderVersionId:string}}>("/api/v1/brands/:brandId/campaigns/:campaignId/assets/:assetId/carousel-review/approve",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return reply.status(201).send(await deps.store.approve(account.id,request.params.brandId,request.params.campaignId,request.params.assetId,version(request.body?.expectedAssetVersion),request.body.renderVersionId))});
 app.post<{Params:{brandId:string;projectId:string};Body:RenderedVersionInput}>("/api/v1/brands/:brandId/carousel-projects/:projectId/rendered-asset-versions",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return reply.status(201).send(await deps.store.saveRenderedVersion(account.id,request.params.brandId,request.params.projectId,request.body))});
 app.post<{Params:{brandId:string;projectId:string};Body:{expectedAssetVersion:number}}>("/api/v1/brands/:brandId/carousel-projects/:projectId/render",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;if(!deps.renderer)throw new DomainValidationError("Production Carousel rendering is not configured");return reply.status(201).send(await deps.renderer.render(account.id,request.params.brandId,request.params.projectId,version(request.body?.expectedAssetVersion)))});
 app.post<{Params:{brandId:string;projectId:string;versionId:string};Body:{expiresInSeconds?:number}}>("/api/v1/brands/:brandId/carousel-projects/:projectId/rendered-asset-versions/:versionId/temporary-delivery",async(request,reply)=>{const account=await auth(request,reply,core,deps.identityVerifier);if(!account)return;return deps.store.temporaryDelivery(account.id,request.params.brandId,request.params.projectId,request.params.versionId,request.body?.expiresInSeconds??900)});
}
function version(value:unknown){if(!Number.isInteger(value)||Number(value)<1)throw new DomainValidationError("expectedAssetVersion must be a positive integer");return Number(value)}
async function auth(request:FastifyRequest,reply:FastifyReply,core:KairoService,verifier:IdentityVerifier){const identity=await verifier.verify(request.headers.authorization);if(!identity){await reply.status(401).send({type:"about:blank",title:"Unauthorized",status:401,detail:"Authentication is required",code:"unauthorized",correlationId:request.id});return null}return core.establishSession(identity)}
