import{describe,expect,it,vi}from"vitest";
import type{ExternalIdentity}from"@kairo/contracts";
import{buildApp}from"./app";
import type{IdentityVerifier}from"./auth";
import{MemoryKairoRepository}from"./store";
import{registerCarouselStudioRoutes}from"./carousel-studio-routes";
import type{PgCarouselStudioStore}from"./carousel-studio-postgres";
class Verifier implements IdentityVerifier{async verify(value:string|undefined):Promise<ExternalIdentity|null>{return value?.startsWith("Bearer test:")?{provider:"test",subject:value.slice(12)}:null}}
describe("VS-77 Carousel Studio routes",()=>{
 it("bootstraps a missing Carousel project from its current Content Asset",async()=>{const core=new MemoryKairoRepository(),verifier=new Verifier(),store={bootstrap:vi.fn().mockResolvedValue({id:"project-1",assetVersion:1})}as unknown as PgCarouselStudioStore,app=buildApp({store:core,identityVerifier:verifier});registerCarouselStudioRoutes(app,{coreStore:core,identityVerifier:verifier,store});const setup=await app.inject({method:"POST",url:"/api/v1/workspaces",headers:{authorization:"Bearer test:alice"},payload:{workspaceName:"Studio",brandName:"Brand"}}),brandId=setup.json().brand.id,response=await app.inject({method:"POST",url:`/api/v1/brands/${brandId}/campaigns/c/assets/a/carousel-review/bootstrap`,headers:{authorization:"Bearer test:alice"}});expect(response.statusCode).toBe(201);expect(store.bootstrap).toHaveBeenCalledWith(expect.any(String),brandId,"c","a");await app.close()});
 it("keeps Carousel Studio routes available when the production renderer is not configured",async()=>{const core=new MemoryKairoRepository(),verifier=new Verifier(),store={getReview:vi.fn().mockResolvedValue({id:"project-1"})}as unknown as PgCarouselStudioStore,app=buildApp({store:core,identityVerifier:verifier});registerCarouselStudioRoutes(app,{coreStore:core,identityVerifier:verifier,store});const setup=await app.inject({method:"POST",url:"/api/v1/workspaces",headers:{authorization:"Bearer test:alice"},payload:{workspaceName:"Studio",brandName:"Brand"}}),brandId=setup.json().brand.id,headers={authorization:"Bearer test:alice"},review=await app.inject({method:"GET",url:`/api/v1/brands/${brandId}/campaigns/c/assets/a/carousel-review`,headers}),render=await app.inject({method:"POST",url:`/api/v1/brands/${brandId}/carousel-projects/project-1/render`,headers,payload:{expectedAssetVersion:1}});expect(review.statusCode).toBe(200);expect(render.statusCode).toBe(400);expect(render.json().detail).toBe("Production Carousel rendering is not configured");await app.close()});
 it("keeps review routes authenticated and forwards optimistic asset versions",async()=>{const core=new MemoryKairoRepository(),verifier=new Verifier(),store={getReview:vi.fn().mockResolvedValue({id:"project-1"}),editText:vi.fn().mockResolvedValue({assetVersion:3})} as unknown as PgCarouselStudioStore,app=buildApp({store:core,identityVerifier:verifier});registerCarouselStudioRoutes(app,{coreStore:core,identityVerifier:verifier,store});expect((await app.inject({method:"GET",url:"/api/v1/brands/x/campaigns/c/assets/a/carousel-review"})).statusCode).toBe(401);const setup=await app.inject({method:"POST",url:"/api/v1/workspaces",headers:{authorization:"Bearer test:alice"},payload:{workspaceName:"Studio",brandName:"Brand"}}),brandId=setup.json().brand.id;const headers={authorization:"Bearer test:alice"};expect((await app.inject({method:"GET",url:`/api/v1/brands/${brandId}/campaigns/c/assets/a/carousel-review`,headers})).statusCode).toBe(200);const edit=await app.inject({method:"PATCH",url:`/api/v1/brands/${brandId}/campaigns/c/assets/a/carousel-review/slides/s1/text`,headers,payload:{expectedAssetVersion:2,headline:"Hook",body:"Body"}});expect(edit.statusCode).toBe(200);expect((store.editText as any).mock.calls[0].slice(1)).toEqual([brandId,"c","a","s1",2,{expectedAssetVersion:2,headline:"Hook",body:"Body"}]);await app.close()});
 it("rejects missing optimistic concurrency input before persistence",async()=>{const core=new MemoryKairoRepository(),verifier=new Verifier(),store={editText:vi.fn()}as unknown as PgCarouselStudioStore,app=buildApp({store:core,identityVerifier:verifier});registerCarouselStudioRoutes(app,{coreStore:core,identityVerifier:verifier,store});const setup=await app.inject({method:"POST",url:"/api/v1/workspaces",headers:{authorization:"Bearer test:bob"},payload:{workspaceName:"Studio",brandName:"Brand"}}),brandId=setup.json().brand.id;const response=await app.inject({method:"PATCH",url:`/api/v1/brands/${brandId}/campaigns/c/assets/a/carousel-review/slides/s1/text`,headers:{authorization:"Bearer test:bob"},payload:{headline:"Hook",body:"Body"}});expect(response.statusCode).toBe(400);expect(store.editText).not.toHaveBeenCalled();await app.close()});
});
