import type{InstagramRecentMedia,InstagramVisualAnalysisPort,InstagramVisualSuggestion}from"./instagram-connection";

export interface InstagramRasterSample{width:number;height:number;pixels:Uint8Array}
export interface InstagramMediaRasterPort{sample(input:{mediaId:string;url:string;maxBytes:number;maxPixels:number}):Promise<InstagramRasterSample|null>}

export class DeterministicInstagramVisualAnalyzer implements InstagramVisualAnalysisPort{constructor(private readonly raster:InstagramMediaRasterPort){}async analyze(media:InstagramRecentMedia[]):Promise<InstagramVisualSuggestion[]>{const samples:Array<{id:string;sample:InstagramRasterSample}>=[];for(const item of media.slice(0,8)){const url=item.thumbnailUrl??item.mediaUrl;if(!url)continue;try{const sample=await this.raster.sample({mediaId:item.id,url,maxBytes:5*1024*1024,maxPixels:2_000_000});if(sample&&validSample(sample))samples.push({id:item.id,sample})}catch{/* One unavailable image must not fabricate or block other evidence. */}}if(!samples.length)return[];const evidenceMediaIds=samples.map(item=>item.id),pixels=samples.flatMap(item=>samplePixels(item.sample)),palette=dominantPalette(pixels),luminance=pixels.reduce((sum,[r,g,b])=>sum+(0.2126*r+0.7152*g+0.0722*b)/255,0)/pixels.length,edgeDensity=samples.reduce((sum,item)=>sum+edges(item.sample),0)/samples.length,confidence=Math.min(.9,.45+samples.length*.05);return[{fieldKey:"color-direction",value:`Observed palette: ${palette.join(", ")}. Confirm these sampled colours before applying them as Brand rules.`,confidence,evidenceMediaIds,method:"bounded-raster-palette-v1"},{fieldKey:"imagery-direction",value:`Recent imagery is ${luminance>.62?"predominantly light":luminance<.38?"predominantly dark":"balanced between light and dark"} in the sampled frames.`,confidence,evidenceMediaIds,method:"bounded-raster-luminance-v1"},{fieldKey:"typography-direction",value:`Sampled imagery has ${edgeDensity>.22?"high":edgeDensity>.1?"moderate":"low"} visual edge density. Treat this only as a text-density direction; the Brand font cannot be identified reliably from these pixels.`,confidence:Math.max(.35,confidence-.15),evidenceMediaIds,method:"bounded-raster-edge-density-v1"}]}}
function validSample(value:InstagramRasterSample){return Number.isInteger(value.width)&&value.width>0&&Number.isInteger(value.height)&&value.height>0&&value.width*value.height<=2_000_000&&value.pixels instanceof Uint8Array&&value.pixels.length===value.width*value.height*3}
function samplePixels(value:InstagramRasterSample){const result:Array<[number,number,number]>=[],step=Math.max(3,Math.floor(value.pixels.length/(4096*3))*3);for(let index=0;index<value.pixels.length;index+=step)result.push([value.pixels[index]!,value.pixels[index+1]!,value.pixels[index+2]!]);return result}
function dominantPalette(pixels:Array<[number,number,number]>){const buckets=new Map<string,number>();for(const[r,g,b]of pixels){const key=[r,g,b].map(value=>Math.min(255,Math.round(value/32)*32)).map(value=>value.toString(16).padStart(2,"0")).join("");buckets.set(key,(buckets.get(key)??0)+1)}return[...buckets.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,3).map(([key])=>`#${key}`)}
function edges(value:InstagramRasterSample){let edges=0,comparisons=0;for(let y=0;y<value.height;y+=Math.max(1,Math.floor(value.height/100)))for(let x=1;x<value.width;x+=Math.max(1,Math.floor(value.width/100))){const a=(y*value.width+x)*3,b=a-3,difference=Math.abs(value.pixels[a]!-value.pixels[b]!)+Math.abs(value.pixels[a+1]!-value.pixels[b+1]!)+Math.abs(value.pixels[a+2]!-value.pixels[b+2]!);if(difference>120)edges++;comparisons++}return comparisons?edges/comparisons:0}
