import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { ResourceNotFoundError } from "@kairo/domain";
import type { InstagramConnectionCandidate, InstagramConnectionRepository, InstagramCredentialVault, InstagramOAuthIntent } from "./instagram-connection";

export class PgEncryptedChannelCredentialVault implements InstagramCredentialVault {
  private readonly key: Buffer;
  constructor(private readonly pool: Pool, encodedKey: string, private readonly now: () => Date = () => new Date()) { this.key = decodeKey(encodedKey); }
  async store(workspaceId:string,brandId:string,credentialRef:string,plaintext:string){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",this.key,iv);cipher.setAAD(Buffer.from(aad(workspaceId,brandId,credentialRef)));const encrypted=Buffer.concat([cipher.update(plaintext,"utf8"),cipher.final()]),tag=cipher.getAuthTag(),at=this.now().toISOString(),provider=credentialProvider(credentialRef);await this.pool.query(`insert into channel_credentials(credential_ref,workspace_id,brand_id,provider,ciphertext,iv,auth_tag,created_at,updated_at,revoked_at) values($1,$2,$3,$4,$5,$6,$7,$8,$8,null) on conflict(credential_ref) do update set provider=excluded.provider,ciphertext=excluded.ciphertext,iv=excluded.iv,auth_tag=excluded.auth_tag,updated_at=excluded.updated_at,revoked_at=null where channel_credentials.workspace_id=excluded.workspace_id and channel_credentials.brand_id=excluded.brand_id`,[credentialRef,workspaceId,brandId,provider,encrypted.toString("base64"),iv.toString("base64"),tag.toString("base64"),at])}
  async resolve(credentialRef:string){const result=await this.pool.query(`select workspace_id,brand_id,ciphertext,iv,auth_tag from channel_credentials where credential_ref=$1 and revoked_at is null`,[credentialRef]),row=result.rows[0];if(!row)throw new Error("Channel credential is unavailable");try{const decipher=createDecipheriv("aes-256-gcm",this.key,Buffer.from(row.iv,"base64"));decipher.setAAD(Buffer.from(aad(row.workspace_id,row.brand_id,credentialRef)));decipher.setAuthTag(Buffer.from(row.auth_tag,"base64"));return Buffer.concat([decipher.update(Buffer.from(row.ciphertext,"base64")),decipher.final()]).toString("utf8")}catch{throw new Error("Channel credential could not be decrypted")}}
  async revoke(credentialRef:string){await this.pool.query(`update channel_credentials set revoked_at=coalesce(revoked_at,$2),updated_at=$2 where credential_ref=$1`,[credentialRef,this.now().toISOString()])}
}

export class PgInstagramConnectionRepository implements InstagramConnectionRepository {
  constructor(private readonly pool:Pool){}
  async createIntent(intent:InstagramOAuthIntent){await this.pool.query(`insert into channel_oauth_intents(id,workspace_id,brand_id,account_id,provider,auth_method,state_hash,expires_at,created_at) values($1,$2,$3,$4,$5,'facebook-instagram',$6,$7,$8)`,[intent.id,intent.workspaceId,intent.brandId,intent.accountId,intent.provider,intent.stateHash,intent.expiresAt,intent.createdAt])}
  async consumeIntent(accountId:string,stateHash:string,at:string){const result=await this.pool.query(`update channel_oauth_intents set consumed_at=$3 where account_id=$1 and state_hash=$2 and provider='meta-instagram' and consumed_at is null and expires_at >= $3 returning *`,[accountId,stateHash,at]);return result.rows[0]?intent(result.rows[0]):null}
  async saveCandidates(candidates:InstagramConnectionCandidate[]){if(!candidates.length)return;const client=await this.pool.connect();try{await client.query("begin");for(const candidate of candidates)await client.query(`insert into channel_oauth_candidates(id,intent_id,workspace_id,brand_id,account_id,page_ref,page_name,account_ref,display_name,username,credential_ref,insights_credential_ref,token_expires_at,granted_scopes,created_at,target_channel,auth_method) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15,'instagram','facebook-login')`,[candidate.id,candidate.intentId,candidate.workspaceId,candidate.brandId,candidate.accountId,candidate.pageRef,candidate.pageName,candidate.accountRef,candidate.displayName,candidate.username??null,candidate.credentialRef,candidate.insightsCredentialRef,candidate.tokenExpiresAt,JSON.stringify(candidate.grantedScopes),candidate.createdAt]);await client.query("commit")}catch(error){await rollback(client);throw error}finally{client.release()}}
  async listCandidates(accountId:string,brandId:string,intentId:string){const result=await this.pool.query(`select c.* from channel_oauth_candidates c join channel_oauth_intents i on i.id=c.intent_id and i.account_id=c.account_id and i.brand_id=c.brand_id where c.account_id=$1 and c.brand_id=$2 and c.intent_id=$3 and i.expires_at >= current_timestamp order by c.created_at,c.id`,[accountId,brandId,intentId]);return result.rows.map(candidate)}
  async markSelected(accountId:string,brandId:string,candidateId:string,at:string){const result=await this.pool.query(`update channel_oauth_candidates c set selected_at=$4 from channel_oauth_intents i where i.id=c.intent_id and i.expires_at >= $4 and c.token_expires_at > $4 and c.account_id=$1 and c.brand_id=$2 and c.id=$3 and c.selected_at is null and not exists(select 1 from channel_oauth_candidates other where other.intent_id=c.intent_id and other.selected_at is not null) returning c.*`,[accountId,brandId,candidateId,at]);return result.rows[0]?candidate(result.rows[0]):null}
  async releaseSelection(accountId:string,brandId:string,candidateId:string){await this.pool.query(`update channel_oauth_candidates set selected_at=null where account_id=$1 and brand_id=$2 and id=$3`,[accountId,brandId,candidateId])}
  async connectionCredentials(accountId:string,brandId:string,channelAccountId:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select credential_ref,insights_credential_ref from channel_accounts where workspace_id=$1 and brand_id=$2 and id=$3 and channel='instagram'`,[workspaceId,brandId,channelAccountId]);return refs(result.rows[0])}finally{client.release()}}
  async connectionCredentialsByAccountRef(accountId:string,brandId:string,accountRef:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select credential_ref,insights_credential_ref from channel_accounts where workspace_id=$1 and brand_id=$2 and channel='instagram' and account_ref=$3`,[workspaceId,brandId,accountRef]);return refs(result.rows[0])}finally{client.release()}}
  async connectionImportTarget(accountId:string,brandId:string,channelAccountId:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select account_ref,provider_page_ref,credential_ref from channel_accounts where workspace_id=$1 and brand_id=$2 and id=$3 and channel='instagram' and status in ('connected','reconnect-required')`,[workspaceId,brandId,channelAccountId]),row=result.rows[0];return row?.account_ref&&row?.provider_page_ref&&row?.credential_ref?{accountRef:String(row.account_ref),pageRef:String(row.provider_page_ref),credentialRef:String(row.credential_ref)}:null}finally{client.release()}}
  async disableConnection(accountId:string,brandId:string,channelAccountId:string,at:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`update channel_accounts set status='disabled',last_verified_at=$4 where workspace_id=$1 and brand_id=$2 and id=$3 and channel='instagram' returning id`,[workspaceId,brandId,channelAccountId,at]);if(!result.rowCount)throw new ResourceNotFoundError("Instagram connection not found")}finally{client.release()}}
  async recordConnectionMetadata(accountId:string,brandId:string,accountRef:string,input:{pageRef:string;username?:string;grantedScopes:string[];insightsCredentialRef:string;tokenExpiresAt:string;verifiedAt:string}){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`update channel_accounts set provider_page_ref=$4,username=$5,granted_scopes=$6::jsonb,insights_credential_ref=$7,token_expires_at=$8,last_verified_at=$9 where workspace_id=$1 and brand_id=$2 and channel='instagram' and account_ref=$3`,[workspaceId,brandId,accountRef,input.pageRef,input.username??null,JSON.stringify(input.grantedScopes),input.insightsCredentialRef,input.tokenExpiresAt,input.verifiedAt]);if(!result.rowCount)throw new ResourceNotFoundError("Instagram connection not found")}finally{client.release()}}
  async purgeExpiredPendingCredentials(at:string){const result=await this.pool.query(`with stale_refs as (select c.credential_ref as ref from channel_oauth_candidates c join channel_oauth_intents i on i.id=c.intent_id where c.selected_at is null and i.expires_at < $1 union select c.insights_credential_ref as ref from channel_oauth_candidates c join channel_oauth_intents i on i.id=c.intent_id where c.selected_at is null and i.expires_at < $1) update channel_credentials cc set revoked_at=coalesce(cc.revoked_at,$1),updated_at=$1 where cc.credential_ref in(select ref from stale_refs) and cc.revoked_at is null returning cc.credential_ref`,[at]);return result.rowCount??0}
  async markExpiredConnectionsReconnectRequired(at:string){const result=await this.pool.query(`update channel_accounts set status='reconnect-required',last_verified_at=$1 where channel='instagram' and status='connected' and token_expires_at is not null and token_expires_at <= $1 returning id`,[at]);return result.rowCount??0}
}
function intent(row:any):InstagramOAuthIntent{return{id:row.id,workspaceId:row.workspace_id,brandId:row.brand_id,accountId:row.account_id,provider:"meta-instagram",stateHash:row.state_hash,expiresAt:iso(row.expires_at),createdAt:iso(row.created_at),...(row.consumed_at?{consumedAt:iso(row.consumed_at)}:{})}}
function candidate(row:any):InstagramConnectionCandidate{return{id:row.id,intentId:row.intent_id,workspaceId:row.workspace_id,brandId:row.brand_id,accountId:row.account_id,pageRef:row.page_ref,pageName:row.page_name,accountRef:row.account_ref,displayName:row.display_name,...(row.username?{username:row.username}:{}),credentialRef:row.credential_ref,insightsCredentialRef:row.insights_credential_ref,tokenExpiresAt:iso(row.token_expires_at),grantedScopes:Array.isArray(row.granted_scopes)?row.granted_scopes:[],createdAt:iso(row.created_at),...(row.selected_at?{selectedAt:iso(row.selected_at)}:{})}}
function refs(row:any):string[]{if(!row)return[];return [...new Set([row.credential_ref,row.insights_credential_ref].filter((value):value is string=>typeof value==="string"&&!!value.trim()))]}
function decodeKey(value:string){const key=Buffer.from(value.trim(),"base64");if(key.length!==32)throw new Error("CHANNEL_CREDENTIAL_ENCRYPTION_KEY must be base64 for exactly 32 bytes");return key}
function aad(workspaceId:string,brandId:string,credentialRef:string){return`${workspaceId}\u0000${brandId}\u0000${credentialRef}`}
function credentialProvider(credentialRef:string){if(credentialRef.startsWith("meta-instagram-login:"))return"meta-instagram-login";if(credentialRef.startsWith("meta-facebook:")||credentialRef.startsWith("meta-facebook-user:"))return"meta-facebook";return"meta-instagram"}
async function scope(client:PoolClient,accountId:string,brandId:string){const result=await client.query(`select b.workspace_id from brands b join workspace_memberships m on m.workspace_id=b.workspace_id where m.account_id=$1 and m.active=true and b.id=$2`,[accountId,brandId]);if(!result.rows[0])throw new ResourceNotFoundError("Brand not found");return result.rows[0].workspace_id as string}
function iso(value:Date|string){return value instanceof Date?value.toISOString():new Date(value).toISOString()}
async function rollback(client:PoolClient){try{await client.query("rollback")}catch{}}
