import type { Pool,PoolClient } from "pg";
import { ResourceNotFoundError } from "@kairo/domain";
import type { MetaConnectionCandidate,MetaConnectionHealth,MetaConnectionRepository,MetaOAuthIntent,MetaConnectionMode,MetaAuthMethod } from "./meta-channel-connection";

export class PgMetaConnectionRepository implements MetaConnectionRepository{
 constructor(private pool:Pool){}
 async createIntent(value:MetaOAuthIntent){await this.pool.query(`insert into channel_oauth_intents(id,workspace_id,brand_id,account_id,provider,auth_method,state_hash,expires_at,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[value.id,value.workspaceId,value.brandId,value.accountId,value.provider,value.mode,value.stateHash,value.expiresAt,value.createdAt])}
 async consumeIntent(accountId:string,stateHash:string,at:string){const result=await this.pool.query(`update channel_oauth_intents set consumed_at=$3 where account_id=$1 and state_hash=$2 and provider in('meta-instagram-login','meta-facebook') and consumed_at is null and expires_at >= $3 returning *`,[accountId,stateHash,at]);return result.rows[0]?intent(result.rows[0]):null}
 async saveCandidates(values:MetaConnectionCandidate[]){if(!values.length)return;const client=await this.pool.connect();try{await client.query("begin");for(const value of values)await client.query(`insert into channel_oauth_candidates(id,intent_id,workspace_id,brand_id,account_id,page_ref,page_name,account_ref,display_name,username,credential_ref,insights_credential_ref,token_expires_at,granted_scopes,created_at,target_channel,auth_method) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15,$16,$17)`,[value.id,value.intentId,value.workspaceId,value.brandId,value.accountId,value.pageRef??null,value.pageName??null,value.accountRef,value.displayName,value.username??null,value.credentialRef,value.insightsCredentialRef,value.tokenExpiresAt,JSON.stringify(value.grantedScopes),value.createdAt,value.channel,value.authMethod]);await client.query("commit")}catch(error){await rollback(client);throw error}finally{client.release()}}
 async listCandidates(accountId:string,brandId:string,intentId:string){const result=await this.pool.query(`select c.* from channel_oauth_candidates c join channel_oauth_intents i on i.id=c.intent_id and i.account_id=c.account_id and i.brand_id=c.brand_id where c.account_id=$1 and c.brand_id=$2 and c.intent_id=$3 and i.expires_at >= current_timestamp order by c.created_at,c.id`,[accountId,brandId,intentId]);return result.rows.map(candidate)}
 async markSelected(accountId:string,brandId:string,candidateId:string,at:string){const result=await this.pool.query(`update channel_oauth_candidates c set selected_at=$4 from channel_oauth_intents i where i.id=c.intent_id and i.expires_at >= $4 and c.token_expires_at > $4 and c.account_id=$1 and c.brand_id=$2 and c.id=$3 and c.selected_at is null and not exists(select 1 from channel_oauth_candidates other where other.intent_id=c.intent_id and other.selected_at is not null) returning c.*`,[accountId,brandId,candidateId,at]);return result.rows[0]?candidate(result.rows[0]):null}
 async releaseSelection(accountId:string,brandId:string,candidateId:string){await this.pool.query(`update channel_oauth_candidates set selected_at=null where account_id=$1 and brand_id=$2 and id=$3`,[accountId,brandId,candidateId])}
 async recordMetadata(accountId:string,brandId:string,accountRef:string,channel:"instagram"|"facebook",input:{authMethod:MetaAuthMethod;pageRef?:string;username?:string;grantedScopes:string[];insightsCredentialRef:string;tokenExpiresAt:string;verifiedAt:string}){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId);const result=await client.query(`update channel_accounts set auth_method=$5,provider_page_ref=$6,username=$7,granted_scopes=$8::jsonb,insights_credential_ref=$9,token_expires_at=$10,last_verified_at=$11 where workspace_id=$1 and brand_id=$2 and channel=$3 and account_ref=$4`,[workspaceId,brandId,channel,accountRef,input.authMethod,input.pageRef??null,input.username??null,JSON.stringify(input.grantedScopes),input.insightsCredentialRef,input.tokenExpiresAt,input.verifiedAt]);if(!result.rowCount)throw new ResourceNotFoundError("Meta connection not found")}finally{client.release()}}
  async connectionCredentials(accountId:string,brandId:string,id:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select credential_ref,insights_credential_ref from channel_accounts where workspace_id=$1 and brand_id=$2 and id=$3 and channel in('instagram','facebook')`,[workspaceId,brandId,id]),row=result.rows[0];return[...new Set([row?.credential_ref,row?.insights_credential_ref].filter((value):value is string=>typeof value==="string"&&!!value.trim()))]}finally{client.release()}}
  async connectionCredentialsByTarget(accountId:string,brandId:string,channel:"instagram"|"facebook",accountRef:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select credential_ref,insights_credential_ref from channel_accounts where workspace_id=$1 and brand_id=$2 and channel=$3 and account_ref=$4`,[workspaceId,brandId,channel,accountRef]),row=result.rows[0];return[...new Set([row?.credential_ref,row?.insights_credential_ref].filter((value):value is string=>typeof value==="string"&&!!value.trim()))]}finally{client.release()}}
 async disable(accountId:string,brandId:string,id:string,at:string){const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`update channel_accounts set status='disabled',last_verified_at=$4 where workspace_id=$1 and brand_id=$2 and id=$3 and channel in('instagram','facebook') returning id`,[workspaceId,brandId,id,at]);if(!result.rowCount)throw new ResourceNotFoundError("Meta connection not found")}finally{client.release()}}
 async health(accountId:string,brandId:string):Promise<MetaConnectionHealth[]>{const client=await this.pool.connect();try{const workspaceId=await scope(client,accountId,brandId),result=await client.query(`select ca.id,ca.channel,ca.auth_method,ca.account_ref,ca.display_name,ca.status,ca.token_expires_at,ca.last_verified_at,ca.granted_scopes,source.status source_status,source.updated_at source_updated_at
 from channel_accounts ca
 left join lateral (
   select status,updated_at from knowledge_sources
   where workspace_id=ca.workspace_id and brand_id=ca.brand_id
     and content_type='application/vnd.kairo.instagram-profile+json'
     and raw_content::jsonb->>'accountRef'=ca.account_ref
   order by updated_at desc,id desc limit 1
 ) source on ca.channel='instagram'
 where ca.workspace_id=$1 and ca.brand_id=$2 and ca.channel in('instagram','facebook') and ca.status<>'disabled' order by ca.connected_at,ca.id`,[workspaceId,brandId]);return result.rows.map(row=>mapMetaConnectionHealth(row))}finally{client.release()}}
}
function intent(row:any):MetaOAuthIntent{return{id:row.id,workspaceId:row.workspace_id,brandId:row.brand_id,accountId:row.account_id,provider:row.provider,mode:row.auth_method as MetaConnectionMode,stateHash:row.state_hash,expiresAt:iso(row.expires_at),createdAt:iso(row.created_at),...(row.consumed_at?{consumedAt:iso(row.consumed_at)}:{})}}
function candidate(row:any):MetaConnectionCandidate{return{id:row.id,intentId:row.intent_id,workspaceId:row.workspace_id,brandId:row.brand_id,accountId:row.account_id,channel:row.target_channel,authMethod:row.auth_method,accountRef:row.account_ref,displayName:row.display_name,...(row.page_ref?{pageRef:row.page_ref}:{}),...(row.page_name?{pageName:row.page_name}:{}),...(row.username?{username:row.username}:{}),credentialRef:row.credential_ref,insightsCredentialRef:row.insights_credential_ref,tokenExpiresAt:iso(row.token_expires_at),grantedScopes:Array.isArray(row.granted_scopes)?row.granted_scopes:[],createdAt:iso(row.created_at),...(row.selected_at?{selectedAt:iso(row.selected_at)}:{})}}
export function mapMetaConnectionHealth(row:any,now=Date.now()):MetaConnectionHealth{const expired=Boolean(row.token_expires_at)&&Date.parse(iso(row.token_expires_at))<=now;const issue=row.status!=="connected"?"reconnect-required":expired?"token-expired":row.source_status==="failed"||row.source_status==="quarantined"?"source-sync-failed":undefined;return{id:String(row.id),channel:row.channel,authMethod:row.auth_method??"facebook-login",accountRef:String(row.account_ref),displayName:String(row.display_name),status:String(row.status),grantedScopes:Array.isArray(row.granted_scopes)?row.granted_scopes.filter((value:unknown):value is string=>typeof value==="string"):[],...(row.token_expires_at?{tokenExpiresAt:iso(row.token_expires_at)}:{}),...(row.last_verified_at?{lastVerifiedAt:iso(row.last_verified_at)}:{}),...(row.source_updated_at?{lastSourceSyncAt:iso(row.source_updated_at)}:{}),...(row.source_status?{sourceStatus:String(row.source_status)}:{}),healthy:!issue,...(issue?{issue}: {})}}
async function scope(client:PoolClient,accountId:string,brandId:string){const result=await client.query(`select b.workspace_id from brands b join workspace_memberships m on m.workspace_id=b.workspace_id where m.account_id=$1 and m.active=true and b.id=$2`,[accountId,brandId]);if(!result.rows[0])throw new ResourceNotFoundError("Brand not found");return String(result.rows[0].workspace_id)}
function iso(value:Date|string){return value instanceof Date?value.toISOString():new Date(value).toISOString()}
async function rollback(client:PoolClient){try{await client.query("rollback")}catch{}}
