import{describe,expect,it,vi}from"vitest";
import{MetaDirectInstagramOAuthClient,metaDirectInstagramRequestedScopes}from"./meta-direct-instagram-oauth";

function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}})}
describe("MetaDirectInstagramOAuthClient",()=>{
 it("uses Instagram Login without Facebook Page permissions",()=>{const client=new MetaDirectInstagramOAuthClient("123","secret","v24.0","https://app.test/channels/meta/instagram/callback",vi.fn());const url=new URL(client.authorizationUrl("state-value"));expect(url.origin).toBe("https://www.instagram.com");expect(url.searchParams.get("scope")?.split(",")).toEqual(metaDirectInstagramRequestedScopes());expect(url.searchParams.get("scope")).not.toContain("pages_");expect(url.searchParams.get("state")).toBe("state-value")});
 it("exchanges, extends and discovers a direct Professional identity",async()=>{const fetchImpl=vi.fn().mockResolvedValueOnce(response({access_token:"short",user_id:123,permissions:[...metaDirectInstagramRequestedScopes()]})).mockResolvedValueOnce(response({access_token:"durable",expires_in:5_184_000})).mockResolvedValueOnce(response({id:"456",user_id:"123",username:"brand",name:"Brand"}));const client=new MetaDirectInstagramOAuthClient("123","secret","v24.0","https://app.test/callback",fetchImpl);await expect(client.exchangeAndDiscover("code")).resolves.toMatchObject({accountRef:"123",username:"brand",accessToken:"durable"});expect(String(fetchImpl.mock.calls[0]?.[0])).toBe("https://api.instagram.com/oauth/access_token");expect(String(fetchImpl.mock.calls[1]?.[0])).toContain("https://graph.instagram.com/access_token")});
 it("bounds imported media to 25 and preserves safe media evidence",async()=>{const rows=Array.from({length:30},(_,index)=>({id:String(index+1),caption:`Post ${index+1}`,...(index===0?{media_url:"https://cdn.example/post.jpg",thumbnail_url:"https://cdn.example/thumb.jpg",like_count:12,comments_count:3}: {})}));const fetchImpl=vi.fn().mockResolvedValueOnce(response({id:"123",username:"brand",followers_count:10,media_count:30})).mockResolvedValueOnce(response({data:rows}));const snapshot=await new MetaDirectInstagramOAuthClient("123","secret","v24.0","https://app.test/callback",fetchImpl).readProfileSnapshot("123","token");expect(snapshot.recentMedia).toHaveLength(25);expect(snapshot.recentMedia[0]).toMatchObject({mediaUrl:"https://cdn.example/post.jpg",thumbnailUrl:"https://cdn.example/thumb.jpg",likeCount:12,commentsCount:3});expect(snapshot.recentMedia[1]).not.toHaveProperty("likeCount");expect(snapshot.accountRef).toBe("123");const mediaRequest=new URL(String(fetchImpl.mock.calls[1]?.[0]));expect(mediaRequest.searchParams.get("fields")).toContain("like_count")});
});
