import { createHash, randomBytes, randomUUID } from "node:crypto";
import { DomainValidationError, ResourceNotFoundError } from "@kairo/domain";
import { connectChannelAccount, type ChannelAccount, type PublishCapability } from "@kairo/domain/publishing";
import { validateInstagramVisualSuggestions, type InstagramCredentialVault, type InstagramProfileSnapshot, type InstagramVisualAnalysisPort } from "./instagram-connection";
import { analyzeInstagramSource } from "./instagram-source-intelligence";
import type { DirectInstagramOAuthPort } from "./meta-direct-instagram-oauth";
import type { FacebookConnectionMode, FacebookOAuthPort } from "./meta-facebook-oauth";

export type MetaConnectionMode="instagram"|FacebookConnectionMode;
export type MetaAuthMethod="instagram-login"|"facebook-login";
export interface MetaOAuthIntent{id:string;workspaceId:string;brandId:string;accountId:string;provider:string;mode:MetaConnectionMode;stateHash:string;expiresAt:string;createdAt:string;consumedAt?:string}
export interface MetaConnectionCandidate{id:string;intentId:string;workspaceId:string;brandId:string;accountId:string;channel:"instagram"|"facebook";authMethod:MetaAuthMethod;accountRef:string;displayName:string;pageRef?:string;pageName?:string;username?:string;credentialRef:string;insightsCredentialRef:string;tokenExpiresAt:string;grantedScopes:string[];createdAt:string;selectedAt?:string}
export interface MetaConnectionCandidateView{id:string;channel:"instagram"|"facebook";authMethod:MetaAuthMethod;accountRef:string;displayName:string;pageRef?:string;pageName?:string;username?:string}
export interface MetaConnectionHealth{id:string;channel:"instagram"|"facebook";authMethod:MetaAuthMethod;accountRef:string;displayName:string;status:string;tokenExpiresAt?:string;lastVerifiedAt?:string;grantedScopes:string[];lastSourceSyncAt?:string;sourceStatus?:string;healthy:boolean;issue?:"reconnect-required"|"token-expired"|"source-sync-failed"}
export interface MetaConnectionRepository{
 createIntent(value:MetaOAuthIntent):Promise<void>;consumeIntent(accountId:string,stateHash:string,at:string):Promise<MetaOAuthIntent|null>;saveCandidates(values:MetaConnectionCandidate[]):Promise<void>;listCandidates(accountId:string,brandId:string,intentId:string):Promise<MetaConnectionCandidate[]>;markSelected(accountId:string,brandId:string,candidateId:string,at:string):Promise<MetaConnectionCandidate|null>;releaseSelection(accountId:string,brandId:string,candidateId:string):Promise<void>;recordMetadata(accountId:string,brandId:string,accountRef:string,channel:"instagram"|"facebook",input:{authMethod:MetaAuthMethod;pageRef?:string;username?:string;grantedScopes:string[];insightsCredentialRef:string;tokenExpiresAt:string;verifiedAt:string}):Promise<void>;connectionCredentials(accountId:string,brandId:string,channelAccountId:string):Promise<string[]>;connectionCredentialsByTarget(accountId:string,brandId:string,channel:"instagram"|"facebook",accountRef:string):Promise<string[]>;disable(accountId:string,brandId:string,channelAccountId:string,at:string):Promise<void>;health(accountId:string,brandId:string):Promise<MetaConnectionHealth[]>;
}
interface BrandPort{getBrandForAccount(accountId:string,brandId:string):Promise<{id:string;workspaceId:string}|null>}
interface PublishingPort{saveChannelAccount(accountId:string,channel:ChannelAccount):Promise<ChannelAccount>}
interface KnowledgePort{listKnowledgeSources(accountId:string,brandId:string):Promise<Array<{id:string;status:string;contentType?:string;contentHash?:string}>>;createKnowledgeSource(accountId:string,brandId:string,input:{type:"research";status:"active";title:string;rawContent:string;contentType:string;contentHash:string}):Promise<unknown>;removeKnowledgeSource(accountId:string,brandId:string,sourceId:string):Promise<unknown>}

export class MetaChannelConnectionService{
 private now:()=>Date;private bytes:()=>Uint8Array;private id:()=>string;
 constructor(private deps:{brands:BrandPort;publishing:PublishingPort;knowledge?:KnowledgePort;repo:MetaConnectionRepository;vault:InstagramCredentialVault;directInstagram:DirectInstagramOAuthPort;facebook:FacebookOAuthPort;visualAnalyzer?:InstagramVisualAnalysisPort;now?:()=>Date;stateBytes?:()=>Uint8Array;id?:()=>string}){this.now=deps.now??(()=>new Date());this.bytes=deps.stateBytes??(()=>randomBytes(32));this.id=deps.id??randomUUID}
 async begin(accountId:string,brandId:string,mode:MetaConnectionMode){const brand=await this.deps.brands.getBrandForAccount(text(accountId,"accountId"),text(brandId,"brandId"));if(!brand)throw new ResourceNotFoundError("Brand not found");const state=Buffer.from(this.bytes()).toString("base64url");if(state.length<32)throw new Error("OAuth state entropy is insufficient");const created=this.now();await this.deps.repo.createIntent({id:this.id(),workspaceId:brand.workspaceId,brandId:brand.id,accountId,provider:provider(mode),mode,stateHash:hash(state),createdAt:created.toISOString(),expiresAt:new Date(created.getTime()+600_000).toISOString()});if(mode==="instagram"){if(!this.deps.directInstagram)throw new DomainValidationError("Instagram Login is unavailable");return{authorizationUrl:this.deps.directInstagram.authorizationUrl(state)}}if(!this.deps.facebook)throw new DomainValidationError("Facebook Login is unavailable");return{authorizationUrl:this.deps.facebook.authorizationUrl(state,mode)}}
 async complete(accountId:string,code:string,state:string){const now=this.now(),intent=await this.deps.repo.consumeIntent(text(accountId,"accountId"),hash(text(state,"state",1_000)),now.toISOString());if(!intent||Date.parse(intent.expiresAt)<now.getTime())throw new DomainValidationError("OAuth state is invalid, expired or already used");const candidates:MetaConnectionCandidate[]=[];if(intent.mode==="instagram"){const found=await this.deps.directInstagram.exchangeAndDiscover(text(code,"authorization code",4_096));const ref=`meta-instagram-login:${this.id()}`,expiresAt=new Date(now.getTime()+found.expiresInSeconds*1_000).toISOString();await this.deps.vault.store(intent.workspaceId,intent.brandId,ref,found.accessToken);candidates.push({id:this.id(),intentId:intent.id,workspaceId:intent.workspaceId,brandId:intent.brandId,accountId:intent.accountId,channel:"instagram",authMethod:"instagram-login",accountRef:numeric(found.accountRef),displayName:text(found.displayName,"displayName"),...(found.username?{username:text(found.username,"username")}:{ }),credentialRef:ref,insightsCredentialRef:ref,tokenExpiresAt:expiresAt,grantedScopes:found.grantedScopes,createdAt:now.toISOString()})}else{const found=await this.deps.facebook.exchangeAndDiscover(text(code,"authorization code",4_096),intent.mode),expiresAt=new Date(now.getTime()+found.expiresInSeconds*1_000).toISOString();for(const target of found.targets){const publishRef=`meta-facebook:${this.id()}`,insightsRef=`meta-facebook-user:${this.id()}`;await this.deps.vault.store(intent.workspaceId,intent.brandId,publishRef,target.accessToken);try{await this.deps.vault.store(intent.workspaceId,intent.brandId,insightsRef,found.userAccessToken)}catch(error){await this.deps.vault.revoke(publishRef).catch(()=>undefined);throw error}candidates.push({id:this.id(),intentId:intent.id,workspaceId:intent.workspaceId,brandId:intent.brandId,accountId:intent.accountId,channel:target.channel,authMethod:"facebook-login",accountRef:numeric(target.accountRef),displayName:text(target.displayName,"displayName"),pageRef:numeric(target.pageRef),pageName:text(target.pageName,"pageName"),...(target.username?{username:text(target.username,"username")}:{ }),credentialRef:publishRef,insightsCredentialRef:insightsRef,tokenExpiresAt:expiresAt,grantedScopes:found.grantedScopes,createdAt:now.toISOString()})}}
 try{await this.deps.repo.saveCandidates(candidates)}catch(error){await revoke(this.deps.vault,candidates.flatMap(item=>[item.credentialRef,item.insightsCredentialRef]));throw error}if(!candidates.length)return{status:"no-eligible-account" as const,intentId:intent.id,brandId:intent.brandId};if(candidates.length===1)return{status:"connected" as const,intentId:intent.id,brandId:intent.brandId,connection:await this.select(accountId,intent.brandId,intent.id,candidates[0]!.id)};return{status:"selection-required" as const,intentId:intent.id,brandId:intent.brandId,candidates:candidates.map(view)}}
 async candidates(accountId:string,brandId:string,intentId:string){return(await this.deps.repo.listCandidates(text(accountId,"accountId"),text(brandId,"brandId"),text(intentId,"intentId"))).map(view)}
 async select(accountId:string,brandId:string,intentId:string,candidateId:string){const all=await this.deps.repo.listCandidates(text(accountId,"accountId"),text(brandId,"brandId"),text(intentId,"intentId")),candidate=all.find(item=>item.id===candidateId&&!item.selectedAt);if(!candidate)throw new ResourceNotFoundError("Meta connection candidate not found");const selected=await this.deps.repo.markSelected(accountId,brandId,candidate.id,this.now().toISOString());if(!selected)throw new ResourceNotFoundError("Meta connection candidate not found");const previousRefs=await this.deps.repo.connectionCredentialsByTarget(accountId,brandId,selected.channel,selected.accountRef);let connection:ChannelAccount|undefined;try{const capabilities:PublishCapability[]=selected.channel==="instagram"?["publish-image","publish-carousel","publish-reel"]:["publish-text","publish-image","publish-video"];connection=await this.deps.publishing.saveChannelAccount(accountId,connectChannelAccount({id:this.id(),workspaceId:selected.workspaceId,brandId:selected.brandId,channel:selected.channel,accountRef:selected.accountRef,displayName:selected.username?`@${selected.username}`:selected.displayName,credentialRef:selected.credentialRef,authMethod:selected.authMethod,capabilities,connectedAt:this.now().toISOString()}));await this.deps.repo.recordMetadata(accountId,brandId,selected.accountRef,selected.channel,{authMethod:selected.authMethod,...(selected.pageRef?{pageRef:selected.pageRef}:{}),...(selected.username?{username:selected.username}:{}),grantedScopes:selected.grantedScopes,insightsCredentialRef:selected.insightsCredentialRef,tokenExpiresAt:selected.tokenExpiresAt,verifiedAt:this.now().toISOString()});if(selected.channel==="instagram")await this.importInstagram(accountId,brandId,selected);await revoke(this.deps.vault,previousRefs.filter(ref=>ref!==selected.credentialRef&&ref!==selected.insightsCredentialRef));for(const other of all)if(other.id!==selected.id)await revoke(this.deps.vault,[other.credentialRef,other.insightsCredentialRef]);return connection}catch(error){await this.deps.repo.releaseSelection(accountId,brandId,candidate.id).catch(()=>undefined);await revoke(this.deps.vault,[selected.credentialRef,selected.insightsCredentialRef]);throw error}}
 async disconnect(accountId:string,brandId:string,id:string){const refs=await this.deps.repo.connectionCredentials(text(accountId,"accountId"),text(brandId,"brandId"),text(id,"channelAccountId"));for(const ref of [...new Set(refs)])await this.deps.vault.revoke(ref);await this.deps.repo.disable(accountId,brandId,id,this.now().toISOString())}
 health(accountId:string,brandId:string){return this.deps.repo.health(text(accountId,"accountId"),text(brandId,"brandId"))}
 private async importInstagram(accountId:string,brandId:string,candidate:MetaConnectionCandidate){if(!this.deps.knowledge)return;const token=await this.deps.vault.resolve(candidate.credentialRef);let imported:InstagramProfileSnapshot;if(candidate.authMethod==="instagram-login")imported=await this.deps.directInstagram.readProfileSnapshot(candidate.accountRef,token);else{const port=this.deps.facebook as FacebookOAuthPort&{readProfileSnapshot?:(accountRef:string,token:string,pageRef?:string)=>Promise<InstagramProfileSnapshot>};if(!port.readProfileSnapshot)return;imported=await port.readProfileSnapshot(candidate.accountRef,token,candidate.pageRef)}const visualSuggestions=this.deps.visualAnalyzer?validateInstagramVisualSuggestions(await this.deps.visualAnalyzer.analyze(imported.recentMedia),imported.recentMedia):[],snapshot={...imported,sourceIntelligence:analyzeInstagramSource(imported.recentMedia),...(visualSuggestions.length?{visualSuggestions}: {})},raw=JSON.stringify(snapshot),stable={...snapshot,retrievedAt:undefined},contentHash=createHash("sha256").update(JSON.stringify(stable)).digest("hex"),contentType=`application/vnd.kairo.instagram-profile+json`;const sources=await this.deps.knowledge.listKnowledgeSources(accountId,brandId),previous=sources.filter(item=>item.status==="active"&&item.contentType===contentType);if(previous.some(item=>item.contentHash===contentHash))return;await this.deps.knowledge.createKnowledgeSource(accountId,brandId,{type:"research",status:"active",title:`Instagram profile snapshot: @${snapshot.username??candidate.accountRef}`,rawContent:raw,contentType,contentHash});for(const item of previous)await this.deps.knowledge.removeKnowledgeSource(accountId,brandId,item.id)}
}
export function hash(value:string){return createHash("sha256").update(value).digest("hex")}
function provider(mode:MetaConnectionMode){return mode==="instagram"?"meta-instagram-login":"meta-facebook"}
function view(value:MetaConnectionCandidate):MetaConnectionCandidateView{return{id:value.id,channel:value.channel,authMethod:value.authMethod,accountRef:value.accountRef,displayName:value.displayName,...(value.pageRef?{pageRef:value.pageRef}:{}),...(value.pageName?{pageName:value.pageName}:{}),...(value.username?{username:value.username}:{})}}
function numeric(value:unknown){const normalized=text(value,"accountRef");if(!/^\d+$/.test(normalized))throw new DomainValidationError("Meta account reference must be numeric");return normalized}
function text(value:unknown,field:string,max=300){if(typeof value!=="string"||!value.trim())throw new DomainValidationError(`${field} is required`);const normalized=value.trim();if(normalized.length>max)throw new DomainValidationError(`${field} is too long`);return normalized}
async function revoke(vault:InstagramCredentialVault,refs:string[]){for(const ref of [...new Set(refs)])await vault.revoke(ref).catch(()=>undefined)}
