import type{Pool,PoolClient}from"pg";
import{DomainValidationError,ResourceNotFoundError}from"@kairo/domain";
import{applyCostToBudget,disableAutomation as disableDomain,recordIntervention,requestSafeRetry,type AutomationControl,type CostEvent,type InterventionRecord,type OperationalFailure,type RetryRequest,type WorkflowBudget}from"@kairo/domain/operations";
import type{OperationsStore}from"./operations-store";

export class PgOperationsRepository implements OperationsStore{
 constructor(private readonly pool:Pool){}
 async recordFailure(f:OperationalFailure){await requireBrandScope(this.pool,f.workspaceId,f.brandId);await this.pool.query(`insert into operational_failures(id,workspace_id,brand_id,workflow_id,stage,diagnostic_code,summary,retry_disposition,attempt,max_attempts,state,trace_id,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'failed',$11,$12) on conflict(id) do nothing`,[f.id,f.workspaceId,f.brandId,f.workflowId,f.stage,f.diagnosticCode,f.summary,f.retryDisposition,f.attempt,f.maxAttempts,f.traceId??null,f.occurredAt]);const q=await this.pool.query(`select * from operational_failures where id=$1`,[f.id]);const saved=toFailure(q.rows[0]);if(saved.workspaceId!==f.workspaceId||saved.brandId!==f.brandId||saved.workflowId!==f.workflowId)throw new DomainValidationError("Failure id already exists outside the supplied scope");return saved}
 async listFailures(accountId:string,brandId:string){await requireOwnerBrand(this.pool,accountId,brandId);const q=await this.pool.query(`select * from operational_failures where brand_id=$1 order by occurred_at desc,id`,[brandId]);return q.rows.map(toFailure)}
 async createBudget(accountId:string,b:WorkflowBudget){const ws=await requireOwnerBrand(this.pool,accountId,b.brandId);if(ws!==b.workspaceId)throw new DomainValidationError("Workflow budget is outside the authorised Workspace");await this.pool.query(`insert into workflow_budgets(id,workspace_id,brand_id,workflow_id,currency,limit_micros,spent_micros,version,created_at) values($1,$2,$3,$4,$5,$6,$7,1,$8)`,[b.id,b.workspaceId,b.brandId,b.workflowId,b.currency,b.limitMicros,b.spentMicros,b.createdAt]);return b}
 async listBudgets(accountId:string,brandId:string){await requireOwnerBrand(this.pool,accountId,brandId);const q=await this.pool.query(`select * from workflow_budgets where brand_id=$1 order by workflow_id,currency,id`,[brandId]);return q.rows.map(toBudget)}
 async recordCost(e:CostEvent){const x=await this.pool.connect();try{await x.query("begin");await requireBrandScope(x,e.workspaceId,e.brandId);const prior=await x.query(`select * from workflow_cost_events where id=$1`,[e.id]);if(prior.rows[0]){const p=prior.rows[0];if(p.workspace_id!==e.workspaceId||p.brand_id!==e.brandId||p.workflow_id!==e.workflowId||Number(p.cost_micros)!==e.costMicros)throw new DomainValidationError("Cost event id already exists with different data");const existing=await x.query(`select * from workflow_budgets where brand_id=$1 and workflow_id=$2 and currency=$3`,[e.brandId,e.workflowId,e.currency]);if(!existing.rows[0])throw new ResourceNotFoundError("Workflow budget not found");await x.query("commit");return toBudget(existing.rows[0])}const q=await x.query(`select * from workflow_budgets where workspace_id=$1 and brand_id=$2 and workflow_id=$3 and currency=$4 for update`,[e.workspaceId,e.brandId,e.workflowId,e.currency]);if(!q.rows[0])throw new ResourceNotFoundError("Workflow budget not found");const current=toBudget(q.rows[0]),updated=applyCostToBudget(current,e);await x.query(`insert into workflow_cost_events(id,workspace_id,brand_id,workflow_id,kind,provider,currency,cost_micros,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[e.id,e.workspaceId,e.brandId,e.workflowId,e.kind,e.provider,e.currency,e.costMicros,e.occurredAt]);await x.query(`update workflow_budgets set spent_micros=$2,version=version+1 where id=$1`,[current.id,updated.spentMicros]);await x.query("commit");return updated}catch(error){await rollback(x);throw error}finally{x.release()}}
 async listCosts(accountId:string,brandId:string){await requireOwnerBrand(this.pool,accountId,brandId);const q=await this.pool.query(`select * from workflow_cost_events where brand_id=$1 order by occurred_at desc,id`,[brandId]);return q.rows.map(toCost)}
 async createAutomationControl(accountId:string,c:AutomationControl){const ws=await requireOwnerBrand(this.pool,accountId,c.brandId);if(ws!==c.workspaceId)throw new DomainValidationError("Automation control is outside the authorised Workspace");await this.pool.query(`insert into automation_controls(id,workspace_id,brand_id,automation_key,stage,status,version,created_at) values($1,$2,$3,$4,$5,'enabled',$6,$7)`,[c.id,c.workspaceId,c.brandId,c.automationKey,c.stage,c.version,c.createdAt]);return c}
 async listAutomationControls(accountId:string,brandId:string){await requireOwnerBrand(this.pool,accountId,brandId);const q=await this.pool.query(`select * from automation_controls where brand_id=$1 order by automation_key,id`,[brandId]);return q.rows.map(toControl)}
 async requestRetry(accountId:string,brandId:string,failureId:string,idempotencyKey:string,requestedAt:string){const x=await this.pool.connect();try{await x.query("begin");await requireOwnerBrand(x,accountId,brandId);const q=await x.query(`select * from operational_failures where id=$1 and brand_id=$2 for share`,[failureId,brandId]);if(!q.rows[0])throw new ResourceNotFoundError("Operational failure not found");const failure=toFailure(q.rows[0]),retry=requestSafeRetry(failure,{actorType:"operator",actorId:accountId,idempotencyKey,requestedAt});const ins=await x.query(`insert into retry_requests(id,workspace_id,brand_id,workflow_id,failure_id,attempt,idempotency_key,requested_by_account_id,requested_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(failure_id,idempotency_key) do nothing returning *`,[retry.id,retry.workspaceId,retry.brandId,retry.workflowId,retry.failureId,retry.attempt,retry.idempotencyKey,retry.requestedBy,retry.requestedAt]);if(!ins.rows[0]){const prior=await x.query(`select * from retry_requests where failure_id=$1 and idempotency_key=$2`,[failureId,idempotencyKey]);await x.query("commit");return toRetry(prior.rows[0])}const audit=recordIntervention({id:`intervention:${retry.id}`,workspaceId:retry.workspaceId,brandId:retry.brandId,actorType:"operator",actorId:accountId,action:"retry-requested",targetType:"workflow",targetId:retry.workflowId,reason:"Safe retry requested",at:requestedAt,relatedFailureId:failureId});await insertIntervention(x,audit);await x.query("commit");return retry}catch(error){await rollback(x);throw error}finally{x.release()}}
 async disableAutomation(accountId:string,brandId:string,automationKey:string,expectedVersion:number,reason:string,at:string){const x=await this.pool.connect();try{await x.query("begin");await requireOwnerBrand(x,accountId,brandId);const q=await x.query(`select * from automation_controls where brand_id=$1 and automation_key=$2 for update`,[brandId,automationKey]);if(!q.rows[0])throw new ResourceNotFoundError("Automation control not found");const current=toControl(q.rows[0]),next=disableDomain(current,{actorType:"operator",actorId:accountId,reason,at,expectedVersion});await x.query(`update automation_controls set status='disabled',version=$2,disabled_at=$3,disabled_by_account_id=$4,disabled_reason=$5 where id=$1 and version=$6`,[current.id,next.version,next.disabledAt,next.disabledBy,next.disabledReason,current.version]);const audit=recordIntervention({id:`intervention:disable:${current.id}:${next.version}`,workspaceId:next.workspaceId,brandId:next.brandId,actorType:"operator",actorId:accountId,action:"automation-disabled",targetType:"automation",targetId:next.automationKey,reason,at});await insertIntervention(x,audit);await x.query("commit");return next}catch(error){await rollback(x);throw error}finally{x.release()}}
 async listInterventions(accountId:string,brandId:string){await requireOwnerBrand(this.pool,accountId,brandId);const q=await this.pool.query(`select * from operator_interventions where brand_id=$1 order by occurred_at desc,id`,[brandId]);return q.rows.map(toIntervention)}
}

async function requireOwnerBrand(db:Pool|PoolClient,accountId:string,brandId:string){const q=await db.query<{workspace_id:string}>(`select b.workspace_id from brands b join workspace_memberships m on m.workspace_id=b.workspace_id where b.id=$2 and m.account_id=$1 and m.active=true and m.role='owner'`,[accountId,brandId]);if(!q.rows[0])throw new ResourceNotFoundError("Pilot operations not found");return q.rows[0].workspace_id}
async function requireBrandScope(db:Pool|PoolClient,workspaceId:string,brandId:string){const q=await db.query(`select 1 from brands where id=$1 and workspace_id=$2`,[brandId,workspaceId]);if(!q.rows[0])throw new ResourceNotFoundError("Brand not found")}
async function insertIntervention(x:PoolClient,a:InterventionRecord){await x.query(`insert into operator_interventions(id,workspace_id,brand_id,actor_account_id,action,target_type,target_id,reason,related_failure_id,occurred_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[a.id,a.workspaceId,a.brandId,a.actorId,a.action,a.targetType,a.targetId,a.reason,a.relatedFailureId??null,a.at])}
function toFailure(r:any):OperationalFailure{return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,workflowId:r.workflow_id,stage:r.stage,diagnosticCode:r.diagnostic_code,summary:r.summary,retryDisposition:r.retry_disposition,attempt:Number(r.attempt),maxAttempts:Number(r.max_attempts),state:"failed",occurredAt:iso(r.occurred_at),...(r.trace_id?{traceId:r.trace_id}:{})})}
function toRetry(r:any):RetryRequest{return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,workflowId:r.workflow_id,failureId:r.failure_id,attempt:Number(r.attempt),idempotencyKey:r.idempotency_key,requestedBy:r.requested_by_account_id,requestedAt:iso(r.requested_at)})}
function toControl(r:any):AutomationControl{return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,automationKey:r.automation_key,stage:r.stage,status:r.status,version:Number(r.version),createdAt:iso(r.created_at),...(r.disabled_at?{disabledAt:iso(r.disabled_at),disabledBy:r.disabled_by_account_id,disabledReason:r.disabled_reason}:{})})}
function toBudget(r:any):WorkflowBudget{const limit=Number(r.limit_micros),spent=Number(r.spent_micros),remaining=limit-spent;return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,workflowId:r.workflow_id,currency:r.currency,limitMicros:limit,spentMicros:spent,remainingMicros:remaining,status:remaining===0?"exhausted":"active",createdAt:iso(r.created_at)})}
function toCost(r:any):CostEvent{return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,workflowId:r.workflow_id,kind:r.kind,provider:r.provider,currency:r.currency,costMicros:Number(r.cost_micros),occurredAt:iso(r.occurred_at)})}
function toIntervention(r:any):InterventionRecord{return Object.freeze({id:r.id,workspaceId:r.workspace_id,brandId:r.brand_id,actorType:"operator",actorId:r.actor_account_id,action:r.action,targetType:r.target_type,targetId:r.target_id,reason:r.reason,at:iso(r.occurred_at),...(r.related_failure_id?{relatedFailureId:r.related_failure_id}:{})})}
function iso(v:string|Date){return v instanceof Date?v.toISOString():new Date(v).toISOString()}
async function rollback(x:PoolClient){try{await x.query("rollback")}catch{}}
