import{createHash}from"node:crypto";import{describe,expect,it,vi}from"vitest";import{privateMediaObjectKey,S3PrivateCreativeObjectStore,S3PrivateUploadSigner,S3TemporaryObjectSigner,s3PrivateObjectStorageConfigFromEnv}from"./private-object-storage";
const config={endpoint:"https://objects.example.test",region:"auto",bucket:"kairo-private",accessKeyId:"access-key",secretAccessKey:"secret-key-value",provider:"s3-private"},now=()=>new Date("2026-08-22T20:00:00.000Z");
describe("private S3-compatible creative storage",()=>{
 it("uploads only hash-verified Brand-scoped immutable objects with SigV4",async()=>{const fetcher=vi.fn().mockResolvedValue(new Response(null,{status:200})),store=new S3PrivateCreativeObjectStore(config,{fetch:fetcher,now}),bytes=new TextEncoder().encode("png"),scope=createHash("sha256").update("ws-1\u0000brand-1").digest("hex").slice(0,24),key=`generated/${scope}/carousel/fingerprint/slide.png`;await expect(store.putPrivateObject({workspaceId:"ws-1",brandId:"brand-1",objectKey:key,contentType:"image/png",contentHash:createHash("sha256").update(bytes).digest("hex"),bytes})).resolves.toEqual({objectId:key});const[url,request]=fetcher.mock.calls[0]!;expect(String(url)).toBe(`https://objects.example.test/kairo-private/${key}`);expect(request.headers.authorization).toMatch(/^AWS4-HMAC-SHA256 Credential=access-key\//);expect(JSON.stringify(request)).not.toContain("secret-key-value")});
 it("rejects cross-Brand keys and changed bytes before network access",async()=>{const fetcher=vi.fn(),store=new S3PrivateCreativeObjectStore(config,{fetch:fetcher,now}),bytes=new Uint8Array([1]);await expect(store.putPrivateObject({workspaceId:"ws",brandId:"brand",objectKey:"generated/wrong/carousel/x.png",contentType:"image/png",contentHash:"0".repeat(64),bytes})).rejects.toThrow(/outside Brand scope/);expect(fetcher).not.toHaveBeenCalled()});
 it("issues bounded credential-free signed GET URLs for the configured provider",async()=>{const signer=new S3TemporaryObjectSigner(config,{now}),url=new URL(await signer.sign({storageProvider:"s3-private",objectKey:"generated/scope/carousel/a b.png",expiresInSeconds:99_999}));expect(url.protocol).toBe("https:");expect(url.searchParams.get("X-Amz-Expires")).toBe("3600");expect(url.searchParams.get("X-Amz-Signature")).toMatch(/^[a-f0-9]{64}$/);expect(url.toString()).not.toContain("secret-key-value");await expect(signer.sign({storageProvider:"other",objectKey:"generated/a.png",expiresInSeconds:60})).rejects.toThrow(/does not match/)});
 it("issues bounded signed PUT URLs for Brand-scoped reusable media",async()=>{const objectKey=privateMediaObjectKey("ws-1","brand-1","asset-1"),signer=new S3PrivateUploadSigner(config,{now}),url=new URL(await signer.signPut({objectKey,contentType:"image/webp",expiresInSeconds:600}));expect(objectKey).toBe("workspaces/ws-1/brands/brand-1/media/asset-1/original");expect(url.pathname).toBe(`/kairo-private/${objectKey}`);expect(url.searchParams.get("X-Amz-SignedHeaders")).toBe("content-type;host");expect(url.searchParams.get("X-Amz-Expires")).toBe("600");expect(url.searchParams.get("X-Amz-Signature")).toMatch(/^[a-f0-9]{64}$/);expect(url.toString()).not.toContain("secret-key-value")});
 it("rejects unsafe media key path segments",()=>{expect(()=>privateMediaObjectKey("ws/escape","brand","asset")).toThrow(/workspaceId is invalid/)});
 it("fails closed for partial or unsafe production configuration",()=>{expect(s3PrivateObjectStorageConfigFromEnv({})).toBeNull();expect(()=>s3PrivateObjectStorageConfigFromEnv({OBJECT_STORAGE_ENDPOINT:"https://objects.test"})).toThrow(/incomplete/);expect(()=>s3PrivateObjectStorageConfigFromEnv({OBJECT_STORAGE_ENDPOINT:"http://objects.test",OBJECT_STORAGE_REGION:"auto",OBJECT_STORAGE_BUCKET:"bucket",OBJECT_STORAGE_ACCESS_KEY_ID:"key",OBJECT_STORAGE_SECRET_ACCESS_KEY:"secret"})).toThrow(/credential-free HTTPS/)})
});