import type {Pool} from "pg";
import {ConcurrencyConflictError} from "@kairo/domain";
import type {BrandPresenterDto} from"@kairo/contracts/presenter";
import{PgHomeMediaRepository}from"./home-media";
import type {SimpleCreationRequest,SimpleCreationStatus,SimpleCreationStore} from"./simple-creation";

export class PgSimpleCreationStore implements SimpleCreationStore{
 readonly homeMedia:PgHomeMediaRepository;
 constructor(private pool:Pool){this.homeMedia=new PgHomeMediaRepository(pool);}
 async create(v:SimpleCreationRequest){await this.pool.query(`insert into simple_creation_requests(id,account_id,workspace_id,brand_id,goal,input_text,source,content_preference,presenter_id,media_asset_ids,status,idea_id,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13,$13)`,[v.id,v.accountId,v.workspaceId,v.brandId,v.goal,v.input??null,v.source??null,v.contentPreference,v.presenterId??null,JSON.stringify(v.mediaAssetIds??[]),v.status,v.ideaId??null,v.createdAt]);return v;}
 async get(accountId:string,brandId:string,id:string){const r=await this.pool.query(`${select} where r.account_id=$1 and r.brand_id=$2 and r.id=$3`,[accountId,brandId,id]);return r.rows[0]?map(r.rows[0]):null;}
 async claim(workerId:string,leaseSeconds:number){const c=await this.pool.connect();try{await c.query("begin");const r=await c.query(`${select} where r.status not in ('ready','needs-attention') and (r.lease_expires_at is null or r.lease_expires_at<now()) order by r.created_at for update skip locked limit 1`);if(!r.rows[0]){await c.query("commit");return null;}await c.query(`update simple_creation_requests set lease_owner=$2,lease_expires_at=now()+($3*interval '1 second'),attempt=attempt+1,updated_at=now() where id=$1`,[r.rows[0].id,workerId,leaseSeconds]);await c.query("commit");return map({...r.rows[0],lease_owner:workerId,attempt:Number(r.rows[0].attempt)+1});}catch(e){await c.query("rollback");throw e;}finally{c.release();}}
 async advance(id:string,workerId:string,status:SimpleCreationStatus,p:Partial<SimpleCreationRequest>={}){const r=await this.pool.query(`update simple_creation_requests set status=$3,idea_id=coalesce($4,idea_id),recommended_angle_id=coalesce($5,recommended_angle_id),campaign_id=coalesce($6,campaign_id),recommendation=coalesce($7::jsonb,recommendation),failure_reason=coalesce($8,failure_reason),asset_id=coalesce($9,asset_id),lease_owner=case when $3 in ('ready','needs-attention') then null else lease_owner end,lease_expires_at=case when $3 in ('ready','needs-attention') then null else lease_expires_at end,updated_at=now() where id=$1 and lease_owner=$2`,[id,workerId,status,p.ideaId??null,p.recommendedAngleId??null,p.campaignId??null,p.recommendation?JSON.stringify(p.recommendation):null,p.failureReason??null,p.assetId??null]);if(!r.rowCount)throw new Error("Creation lease was lost");}
 async getPresenter(workspaceId:string,brandId:string){const r=await this.pool.query(`${presenterSelect} where workspace_id=$1 and brand_id=$2`,[workspaceId,brandId]);return r.rows[0]?mapPresenter(r.rows[0]):null;}
 async putPresenter(v:BrandPresenterDto,expectedVersion?:number){
  if(expectedVersion===undefined){const r=await this.pool.query(`insert into brand_presenters(id,workspace_id,brand_id,display_name,status,mode,visual_style,voice_style,locale,accent,pace,framing,background,intro_style,outro_style,caption_preference,version,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) on conflict(workspace_id,brand_id) do nothing returning *`,presenterValues(v));if(!r.rows[0])throw new ConcurrencyConflictError("Presenter changed. Refresh and try again.");return mapPresenter(r.rows[0]);}
  const r=await this.pool.query(`update brand_presenters set display_name=$4,status=$5,mode=$6,visual_style=$7,voice_style=$8,locale=$9,accent=$10,pace=$11,framing=$12,background=$13,intro_style=$14,outro_style=$15,caption_preference=$16,version=version+1,updated_at=$19 where workspace_id=$2 and brand_id=$3 and version=$20 returning *`,[v.id,v.workspaceId,v.brandId,v.displayName,v.status,v.mode,v.visualStyle??null,v.voiceStyle??null,v.locale??null,v.accent??null,v.pace??null,v.framing??null,v.background??null,v.introStyle??null,v.outroStyle??null,v.captionPreference??null,v.version,v.createdAt,v.updatedAt,expectedVersion]);if(!r.rows[0])throw new ConcurrencyConflictError("Presenter changed. Refresh and try again.");return mapPresenter(r.rows[0]);
 }
}
const select=`select r.* from simple_creation_requests r`;
const presenterSelect=`select * from brand_presenters`;
function map(r:any):SimpleCreationRequest{return{id:String(r.id),accountId:String(r.account_id),workspaceId:String(r.workspace_id),brandId:String(r.brand_id),goal:String(r.goal),...(r.input_text?{input:String(r.input_text)}:{}),...(r.source?{source:String(r.source)}:{}),contentPreference:r.content_preference,...(r.presenter_id?{presenterId:String(r.presenter_id)}:{}),mediaAssetIds:Array.isArray(r.media_asset_ids)?r.media_asset_ids.map(String):[],status:r.status,...(r.idea_id?{ideaId:String(r.idea_id)}:{}),...(r.recommended_angle_id?{recommendedAngleId:String(r.recommended_angle_id)}:{}),...(r.campaign_id?{campaignId:String(r.campaign_id)}:{}),...(r.asset_id?{assetId:String(r.asset_id)}:{}),...(r.recommendation?{recommendation:r.recommendation}:{}),...(r.failure_reason?{failureReason:String(r.failure_reason)}:{}),attempt:Number(r.attempt),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
function mapPresenter(r:any):BrandPresenterDto{return{id:String(r.id),workspaceId:String(r.workspace_id),brandId:String(r.brand_id),displayName:String(r.display_name),status:r.status,mode:r.mode,...(r.visual_style?{visualStyle:String(r.visual_style)}:{}),...(r.voice_style?{voiceStyle:String(r.voice_style)}:{}),...(r.locale?{locale:String(r.locale)}:{}),...(r.accent?{accent:String(r.accent)}:{}),...(r.pace?{pace:String(r.pace)}:{}),...(r.framing?{framing:String(r.framing)}:{}),...(r.background?{background:String(r.background)}:{}),...(r.intro_style?{introStyle:String(r.intro_style)}:{}),...(r.outro_style?{outroStyle:String(r.outro_style)}:{}),...(r.caption_preference?{captionPreference:String(r.caption_preference)}:{}),version:Number(r.version),createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
function presenterValues(v:BrandPresenterDto){return[v.id,v.workspaceId,v.brandId,v.displayName,v.status,v.mode,v.visualStyle??null,v.voiceStyle??null,v.locale??null,v.accent??null,v.pace??null,v.framing??null,v.background??null,v.introStyle??null,v.outroStyle??null,v.captionPreference??null,v.version,v.createdAt,v.updatedAt];}
