import { readFile } from "node:fs/promises";
import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { createCampaign, createContentAsset, createInitialContentVersion } from "@kairo/domain/campaign";
import { PgKairoRepository } from "./postgres-store";
import { PgResearchRepository } from "./research-postgres-store";
import { PgCampaignRepository } from "./campaign-postgres-store";
import { createIdea, createResearchDossier, type Angle } from "@kairo/domain/research";

const connectionString=process.env.TEST_DATABASE_URL; const describePg=connectionString?describe:describe.skip;
describePg("PostgreSQL VS-05 Campaign repository",()=>{
 const pool=new Pool({connectionString}); const core=new PgKairoRepository(pool); const research=new PgResearchRepository(pool); const repo=new PgCampaignRepository(pool);
 beforeAll(async()=>{const exists=await pool.query<{name:string|null}>("select to_regclass('public.campaigns')::text name");if(!exists.rows[0]?.name)for(const file of ["0001_identity_workspace_brand.sql","0002_brand_brain_knowledge.sql","0003_hunter_discover.sql","0004_research_angles.sql","0005_campaign_content.sql","0006_content_review_approval.sql"])await pool.query(await readFile(new URL(`../migrations/${file}`,import.meta.url),"utf8"));});
 beforeEach(async()=>{await pool.query("truncate content_approvals,content_reviews,content_versions,content_assets,campaigns,angles,claim_evidence,claims,evidence_references,research_dossiers,ideas,brand_opportunity_signals,brand_opportunities,public_signals,knowledge_source_derivations,brand_brain_field_sources,brand_brain_fields,knowledge_sources,audit_events,brands,workspace_memberships,workspaces,external_identities,accounts cascade");}); afterAll(()=>pool.end());
 it("persists scoped lineage and rejects stale version appends",async()=>{const account=await core.resolveAccount({provider:"test",subject:"alice"});const made=await core.createWorkspaceWithBrand(account.id,{workspaceName:"Studio",brandName:"Brand"});const idea=createIdea({id:"idea-1",workspaceId:made.workspace.id,brandId:made.brand.id,title:"Idea",premise:"Explain evidence",source:{type:"user"},createdAt:"2026-08-13T10:00:00Z"});await research.createIdea(account.id,idea);const dossier=createResearchDossier({id:"research-1",workspaceId:made.workspace.id,brandId:made.brand.id,ideaId:idea.id,summary:"Supported research",evidence:[{id:"evidence-1",sourceUrl:"https://example.com",sourceTitle:"Source",retrievedAt:"2026-08-13T10:00:00Z"}],claims:[{id:"claim-1",text:"Supported",classification:"fact",confidence:.9,evidenceStrength:"strong",verificationState:"supported",freshness:"fresh",evidenceIds:["evidence-1"],firstPersonAuthorization:"not-applicable"}],unresolvedUncertainties:[],createdAt:"2026-08-13T10:01:00Z"});await research.saveResearchDossier(account.id,dossier);const angle:Angle={id:"angle-1",workspaceId:made.workspace.id,brandId:made.brand.id,ideaId:idea.id,title:"Angle",framing:"Frame",audience:"Founders",objective:"Educate",hookDirection:"Evidence",expectedValue:"Clarity",effort:"low",recommendedFormat:"text",recommendedChannel:"linkedin",supportingClaimIds:["claim-1"],status:"selected",version:1};await research.saveCandidateAngles(account.id,[angle]);const campaign=createCampaign({id:"campaign-1",name:"Campaign",objective:"Educate",lineage:{workspaceId:made.workspace.id,brandId:made.brand.id,ideaId:idea.id,researchId:dossier.id,angleId:angle.id,angleStatus:"selected",supportingClaimIds:["claim-1"]},createdAt:"2026-08-13T10:02:00Z"});await repo.saveCampaign(account.id,campaign);const asset=createContentAsset({id:"asset-1",campaign,channel:"linkedin",format:"text",audience:"Founders",topic:"Evidence",hookType:"data-led",cta:"Read",createdAt:"2026-08-13T10:03:00Z"});const version=createInitialContentVersion({id:"version-1",asset,content:"First",supportingClaimIds:["claim-1"],actor:"user",action:"manual-edit",createdAt:"2026-08-13T10:04:00Z"});await repo.saveAssetWithVersion(account.id,{...asset,currentVersion:1},version);const detail=await repo.getCampaign(account.id,made.brand.id,campaign.id);expect(detail?.assets[0]?.versions).toHaveLength(1);await expect(repo.appendVersion(account.id,made.brand.id,campaign.id,asset.id,0,()=>version)).rejects.toThrow(/stale/i);});
});
